<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>FullProf · diff-ref-struct – diff-ref-struct · Rietveld refinement for the Mac</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<link href="../../assets/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-html-afe927e19676d0e50b1726048be49fb1.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:opsz,wght@8..60,400;8..60,600;8..60,700&amp;family=Source+Sans+3:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;family=IBM+Plex+Mono:wght@400;500&amp;display=swap" rel="stylesheet">
<!-- KaTeX auto-render: publication titles carry TeX inside generated HTML that
     Quarto's own math pipeline never sees (same approach as thermomat). -->
<script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css">
<script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js"></script>
<script defer="" src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js"></script>
<script>
/* The header ribbon is sticky; the side columns and anchor targets need its height. */
(function () {
  function headH() {
    var t = document.querySelector(".topline"), h = document.querySelector(".site-head");
    var px = (t ? t.offsetHeight : 0) + (h ? h.offsetHeight : 0);
    if (px) document.documentElement.style.setProperty("--head-h", px + "px");
  }
  document.addEventListener("DOMContentLoaded", headH);
  window.addEventListener("load", headH);
  window.addEventListener("resize", headH);
})();
document.addEventListener("DOMContentLoaded", function () {
  if (window.renderMathInElement) {
    renderMathInElement(document.body, {
      delimiters: [{ left: "$$", right: "$$", display: true }, { left: "$", right: "$", display: false }, { left: "\\(", right: "\\)", display: false }],
      throwOnError: false
    });
  }
  /* Quarto's KaTeX pipeline writes <span class="math inline">TeX</span> without delimiters and renders
     them in a loop that reads firstChild.data; that loop dies at the first span the auto-render above
     has already turned into KaTeX markup, leaving every later formula raw. Render the rest here. */
  if (window.katex) {
    document.querySelectorAll(".math").forEach(function (el) {
      if (!el.querySelector(".katex")) {
        var t = el.textContent.replace(/^\s*\\[\(\[]/, "").replace(/\\[\)\]]\s*$/, "");
        try { katex.render(t, el, { displayMode: el.classList.contains("display"), throwOnError: false }); } catch (e) {}
      }
      /* Quarto's loop would still visit this span and wipe it (firstChild is now an element, not text):
         take it out of its sight. No stylesheet of the site depends on the class; KaTeX's own output carries the layout. */
      el.classList.remove("math"); el.classList.add("math-done");
    });
  }
});
</script>


<link rel="stylesheet" href="../../assets/styles/theme.css">
<link rel="stylesheet" href="../../assets/styles/site.css">
<link rel="stylesheet" href="../../assets/styles/project.css">
</head>

<body>

<!-- Site header, family kit. Root-absolute hrefs are rewritten by Quarto to
     page-relative links at render time. -->
<div class="topline"></div>
<header class="site-head">
  <div class="site-head__inner">
    <a href="../../index.html" class="wordmark">diff <span class="accent">ref</span> struct
      <span class="wordmark-sub">Rietveld refinement for the Mac · powder diffraction with X-rays, synchrotron and neutrons · started October 2026</span>
    </a>
    <!-- The entries are the groups of data/nav.yml, in the same order; the two navigations say the same thing. -->
    <nav class="site-nav">
      <a href="../../index.html">Overview</a>
      <a href="../../brief/index.html">Brief</a>
      <a href="../../background/index.html">Background</a>
      <span class="nav-pair"><a href="../../design/index.html">Design</a><span class="sl">/</span><a href="../../roadmap/index.html">Roadmap</a></span>
      <a href="../../manual/index.html">Manual</a>
      <span class="nav-right">
        <span class="nav-pair"><a href="../../about/index.html">Method</a><span class="sl">/</span><a href="../../log/index.html">Log</a></span>
        <a href="../../releases/index.html">Release notes</a>
      </span>
    </nav>
  </div>
</header>
<!-- generated by tools/build.py: left navigation + opening of the reading column -->
<div class="docs">
<nav class="docs-nav" aria-label="Site sections">
<button class="docs-fold" type="button" data-fold="nav" aria-label="Hide the navigation" title="Hide the navigation">‹</button>
<details class="group" open=""><summary class="t">Overview</summary><ul><li><a href="../../index.html">Overview</a></li></ul></details>
<details class="group" open=""><summary class="t">Brief</summary><ul><li><a href="../../brief/index.html">The brief, organised</a></li></ul></details>
<details class="group" open=""><summary class="t">Background</summary><ul><li><a href="../../background/index.html">The programs that inspire</a></li><li><a href="../../background/fullprof/index.html">FullProf, the baseline</a></li><li><a href="../../background/gsas2/index.html">GSAS-II</a></li></ul></details>
<details class="group" open=""><summary class="t">Design / Roadmap</summary><ul><li><a href="../../design/index.html">Design: open questions</a></li><li><a href="../../design/proposal/index.html">Proposal (draft)</a></li><li><a href="../../roadmap/index.html">Roadmap: the phases</a></li></ul></details>
<details class="group" open=""><summary class="t">Manual</summary><ul><li><a href="../../manual/index.html">About the manual</a></li><li><a href="../../manual/parameters/index.html">Parameters: the theory</a></li></ul></details>
<details class="group" open=""><summary class="t">Method / Log</summary><ul><li><a href="../../about/index.html">How this site works</a></li><li><a href="../../log/index.html">The log, every dated step</a></li></ul></details>
<details class="group" open=""><summary class="t">Release notes</summary><ul><li><a href="../../releases/index.html">Release notes</a></li></ul></details>
</nav>
<div class="docs-main">

<header id="title-block-header">
<h1 class="title">FullProf</h1>

</header>


<article class="page-wide">
<h1>FullProf, the baseline</h1>
<p class="lede">J. Rodríguez-Carvajal (ILL, formerly LLB); the FullProf Suite with WinPLOTR, EdPCR and FullProfAPP. The complete inventory of what it does for crystal-structure refinement from powder diffraction (log <a href="../../log/index.html#L013">L013</a>, brought up to date with the FullProf News pages 2001–2026 and the FullProfAPP manual in <a href="../../log/index.html#L017">L017</a>; "Since" gives the date a capability appeared after the 2001 manual). One row per capability: what it does, where it is set in the <code>.pcr</code> control file, and the sources in <code>manuals/fullprof/</code> (path, page or line). That folder is kept in the private repository and not published, so the sources are named, not linked. GSAS-II and Jana2020 are read against this list for what FullProf lacks (<a href="../../log/index.html#L012">L012</a>).</p>
<p class="sub"><b>Sources read.</b> The FullProf manual "An introduction to the program FullProf", version July 2001 for FullProf.2k (J. Rodríguez-Carvajal, LLB Saclay; 139 pages, read page by page; the copy FullProf_Manual_1.pdf is byte-identical); FP_COMMANDS.pdf, the list of keywords for the COMMANDS block of a .pcr file (T. Roisnel, 2012–2023, 12 pages); the eleven tutorial folders: 1 WinPLOTR (FPSchool slides, ILL, December 2015, with a sequential example run in 2023), 2 Y2O3 structure solution (undated), 3 Co-doped YBCO (HERCULES course, undated), 4 spinel MgAl2O4 (text exercise, undated), 5 quantitative phase analysis (slides, undated, with papers of 2001 and 2002), 6 microstructure (paper of about 2002), 7 symmetry modes (May 2011), 8 rigid bodies (2002 files, later slides), 9 simulated annealing of organic compounds (outputs of 2017), 10 FullProfAPP (FullProf School, October 2023), 11 FAULTS (FullProf School, April 2025; FAULTS manual September 2018); the FP_tests folder of the FullProf developers (308 files, 130 .pcr, driven by test_fp.bat, listing of March 2025); the FullProf News pages (ILL, January 2001 to May 2026, 27 files in news/, cited by line of the raw .htm, dates as the News gives them); four documents in docs/: TOF_FullProf.pdf ("Dec. 2003 (Draft)", 11 pages), Microstructural_effects.pdf (LLB version of the microstructure paper, undated, PDF of November 2003, 11 pages), GLOpSAnn.pdf (October 2008, updated April 2020, 5 pages), Short_guide_to_MolPDF.pdf (November 2016, 6 pages); and the FullProfAPP manual v1.3.3 (9 June 2025, docs/fullprofapp, HTML cited by line). All of it lies in manuals/fullprof/, which is not published. Every citation below was checked against the page or line it names. "Not in the 2001 manual" marks capabilities seen only in the later material; "Since" gives the first appearance as the News or the document dates it.</p>
<p class="sub">199 entries.</p>
<h2 id="data" class="anchored">Data, radiations and patterns</h2>
<div class="table-wrap">
<table class="inventory caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Capability</th>
<th data-quarto-table-cell-role="th">What it does</th>
<th data-quarto-table-cell-role="th">In the <code>.pcr</code></th>
<th data-quarto-table-cell-role="th">Sources</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Laboratory X-rays, one or two wavelengths</strong></td>
<td>Constant-wavelength X-ray patterns in 2<span class="math inline">\(\theta\)</span> with a single wavelength or a doublet (e.g. Cu Kα1/Kα2): Lambda1, Lambda2 and the intensity ratio I2/I1; Lambda2 = Lambda1 for monochromatic radiation.<br>
<span class="m">The intensity ratio of the two wavelengths is refinable (VARY ratio after the Lambda line) since 10 June 2011 (version 5.10).</span></td>
<td>line 4 Job=0; line 8 Lambda1 Lambda2 Ratio</td>
<td class="cite">FullProf_Manual.pdf, p. 5 · FullProf_Manual.pdf, p. 69 · FullProf_Manual.pdf, p. 75 · y2o3_Ia3.pcr L10–11 · FullProf_News_2011.htm L156–175 · FullProf_News_2011.htm L183–190</td>
</tr>
<tr class="even">
<td><strong>Synchrotron X-rays</strong></td>
<td>Short-wavelength synchrotron patterns refined as X-ray data with the synchrotron polarisation correction; data given as (x, y, <span class="math inline">\(\sigma\)</span>) need Ilo=3 to trigger it.</td>
<td>Job=0 with Ilo=3; line 8 Rpolarz</td>
<td class="cite">FullProf_Manual.pdf, p. 5 · FullProf_Manual.pdf, p. 70 · FullProf_Manual.pdf, p. 76 · piro-a.pcr L4–5</td>
</tr>
<tr class="odd">
<td><strong>Constant-wavelength neutrons</strong></td>
<td>Neutron patterns in 2<span class="math inline">\(\theta\)</span> from reactor diffractometers (nuclear and magnetic scattering); 95 of the 162 pattern lines in FP_tests.</td>
<td>line 4 Job=1</td>
<td class="cite">FullProf_Manual.pdf, p. 5 · FullProf_Manual.pdf, p. 69 · pbso4.pcr L4–5</td>
</tr>
<tr class="even">
<td><strong>Time-of-flight neutrons</strong></td>
<td>Spallation-source patterns with TOF in microseconds as the scattering variable; peak positions from Zero, Dtt1, Dtt2 (and, since 2021, Dtt_1overD/d) and the bank angle 2SinTh, which also enters the Lorentz factor.<br>
<span class="m">TOF_FullProf.pdf (Dec. 2003): only data corrected for the incident spectrum are analysed safely; the incident-spectrum correction is "not tested sufficiently" and raw data are not recommended. Dtt_1overD added 10 January 2021 (version 7.40).</span></td>
<td>line 4 Job=-1, Uni=1; line 14 Zero Dtt1 Dtt2 2SinTh (Dtt_1overD since 7.40)</td>
<td class="cite">FullProf_Manual.pdf, p. 69 · FullProf_Manual.pdf, p. 71 · FullProf_Manual.pdf, pp. 82–83 · alum.pcr L4–5 · TOF_FullProf.pdf, p. 1 · FullProf_News_2021.htm L177–182</td>
</tr>
<tr class="odd">
<td><strong>Energy-dispersive X-rays</strong></td>
<td>Patterns with energy (keV) as the scattering variable, E = Zero + (StE1 + StE2·s)·s with s = 1/d; usable for profile matching (Le Bail) only.<br>
<span class="m">The detector 2<span class="math inline">\(\theta\)</span> may replace 2SinTh (taken as 2<span class="math inline">\(\theta\)</span> when &gt; 2) since 3 July 2004; only the pseudo-Voigt until February 2011, then the TCH Voigt (Npr=7) with microstructural parameters, with energy-dispersive IRF files "not finished"; WinPLOTR-2006 has an energy x-axis since May 2021. No energy-dispersive case in FP_tests.</span></td>
<td>line 4 Uni=2; line 14 Zero StE1 StE2 2SinTh</td>
<td class="cite">FullProf_Manual.pdf, p. 5 · FullProf_Manual.pdf, p. 71 · FullProf_Manual.pdf, p. 82 · Fullprof_News_2004.htm L2529–2562 · FullProf_News_2011.htm L300–309 · FullProf_News_2021.htm L80–86</td>
</tr>
<tr class="even">
<td><strong>Pattern calculation (simulation)</strong></td>
<td>Computes a pattern from the model without data for X-rays, CW or TOF neutrons; with Dum=1 writes CODFIL.sim, the calculated pattern with Poisson noise scaled by the scale factor, reusable as an observed file.</td>
<td>line 4 Job=2, 3 or -3; Dum=1</td>
<td class="cite">FullProf_Manual.pdf, p. 69 · FullProf_Manual.pdf, p. 12 · layer.pcr L3–4</td>
</tr>
<tr class="odd">
<td><strong>Free-format and instrument data files</strong></td>
<td>Reads the intensity file in free format (start, step, end, then counts) or in fixed formats of named instruments: ILL D1A/D2B, D1B, D20, D4, Brookhaven and DBWS synchrotron, a general two-axis format with monitors, PSI DMC, Socabim .uxd, variable counting time, GSAS files, PANalytical (Ins=13, including XRDML); <span class="math inline">\(\sigma\)</span> from counts, detector numbers or monitor ratios.<br>
<span class="m">Data-file extensions other than .dat since January 2001; several patterns in one file (Ins=0, 6, 12) since March 2001; PANalytical formats recognised automatically with Ins=13 since 10 May 2003; .uxd data in counts per second converted to counts since May 2007; several scans in one XRDML file summed since November 2015.</span></td>
<td>line 7 Ins=0–13</td>
<td class="cite">FullProf_Manual.pdf, pp. 73–74 · FullProf_Manual.pdf, pp. 132–137 · y2o3.dat L1–3 · Fullprof_News_2001.htm L1190–1199 · Fullprof_News_2001.htm L733–740 · Fullprof_News_2003.htm L1432–1435 · Fullprof_News_2007.htm L169–174 · FullProf_News_2015.htm L63–65</td>
</tr>
<tr class="even">
<td><strong>x, y, <span class="math inline">\(\sigma\)</span> files with variable step</strong></td>
<td>XYDATA files of (x, y, <span class="math inline">\(\sigma\)</span>) columns with a header; variable step kept or interpolated to a constant step; <span class="math inline">\(\sigma\)</span> = √y when absent.</td>
<td>line 7 Ins=10; XYDATA, INTER keywords in the file</td>
<td class="cite">FullProf_Manual.pdf, p. 74 · alum.dat L1 · EgyptMakeUp.xys L1–5</td>
</tr>
<tr class="odd">
<td><strong>Multi-bank TOF files (GSAS, ISIS)</strong></td>
<td>Several detector banks in one file, read by repeating the file name for each pattern: GSAS files (Ins=12) and the ISIS multibank x, y, <span class="math inline">\(\sigma\)</span> format (Ins=14: title, # comments, BANK blocks); the current tests read Mantid .gss files of WISH this way.<br>
<span class="m">Since 24 September 2003 (Ins=14).</span><br>
<span class="m">Not in the 2001 manual, which stops at Ins=12. Since April 2023 several patterns in one file are allowed for TOF only.</span></td>
<td>line 7n Ins=12 or 14, the same file name per pattern</td>
<td class="cite">Dy2BaCuO5-1p5K.pcr L15–25 · Fullprof_News_2003.htm L674–789 · TOF_FullProf.pdf, p. 1 · FullProf_News_2023.htm L172–176</td>
</tr>
<tr class="even">
<td><strong>Excluded regions</strong></td>
<td>Removes ranges of the scattering variable from the fit (sample-environment peaks, distorted background), given as low/high pairs per pattern.</td>
<td>line 4 Nex; line 11 ALOW AHIGH</td>
<td class="cite">FullProf_Manual.pdf, p. 70 · FullProf_Manual.pdf, p. 78 · Cocuc_LeBail.pcr L16–17</td>
</tr>
<tr class="odd">
<td><strong>Point reduction for fast runs</strong></td>
<td>Uses every Ste-th point (step Ste × Step) for quick preliminary refinements.</td>
<td>line 4 Ste</td>
<td class="cite">FullProf_Manual.pdf, p. 71 · prba10k.pcr L4–5</td>
</tr>
<tr class="even">
<td><strong>Weighting schemes</strong></td>
<td>Standard least squares with w = 1/<span class="math inline">\(\sigma\)</span>², maximum likelihood with weights recomputed each cycle from the calculated counts (Poisson), or a SHELX-like scheme w = 1/[<span class="math inline">\(\sigma\)</span>² + (aP)² + bP + d], P = f·max(0, yobs) + (1−f)·ycalc, with its coefficients on a WGHT line.<br>
<span class="m">In 2001 Iwg=2 meant unit weights (esd's then not multiplied by <span class="math inline">\(\chi^2\)</span>); since 22 March 2012 (version 5.30) Iwg=3 is the SHELX-like scheme and Iwg=2 its defaults a = 0.2, f = 1/3. For powders the News says "even if it has not been tested".</span></td>
<td>line 4 Iwg=0, 1, 2, 3; WGHT a b c d e f</td>
<td class="cite">FullProf_Manual.pdf, p. 70 · FullProf_Manual.pdf, p. 43 · FullProf_Manual.pdf, p. 63 · Al2O3_Psett.pcr L4–5 · FullProf_News_2012.htm L255–305</td>
</tr>
<tr class="odd">
<td><strong>Multi-pattern refinement</strong></td>
<td>Refines several patterns at once (e.g. TOF neutron banks with synchrotron X-rays) with a weight per pattern summing to 1: <span class="math inline">\(\chi^2\)</span>_T = Σ <span class="math inline">\(\omega\)</span>_P <span class="math inline">\(\chi^2\)</span>_P plus the restraint term; each pattern has its own flags, data file, IRF and profile parameters.<br>
<span class="m">Limits: 16 phases and 7 patterns (March 2001), 25 patterns (October 2002), 50 by November 2006. The .pcr and the data may sit in different directories since June 2020; output files take the multi-pattern names even for one pattern since February 2025.</span></td>
<td>line 2 NPATT n; line 3 W_PAT w1…wn; per-pattern lines 4n, 7n, 8n…</td>
<td class="cite">FullProf_Manual.pdf, p. 6 · FullProf_Manual.pdf, p. 42 · FullProf_Manual.pdf, pp. 66–67 · gabriela.pcr L3–11 · Fullprof_News_2001.htm L695–698 · Fullprof_News_2002.htm L276–294 · Fullprof_News_2006.htm L15–21 · FullProf_News_2020.htm L82–84 · FullProf_News_2025.htm L68–70</td>
</tr>
<tr class="even">
<td><strong>Patterns switched on or off</strong></td>
<td>A flag per pattern on the NPATT line says whether the pattern is refined (1) or excluded (0), so one .pcr keeps all patterns; the weights of the patterns used are renormalised to sum to 1.<br>
<span class="m">Since 12 March 2001 (version 1.9b); flags always written since 12 October 2003 (version 2.50).</span></td>
<td>line 2 NPATT n f1 … fn</td>
<td class="cite">Fullprof_News_2001.htm L720–725 · Fullprof_News_2003.htm L255–277</td>
</tr>
<tr class="odd">
<td><strong>Joint X-ray and neutron refinement</strong></td>
<td>Patterns of different radiations in one refinement by giving each pattern its own Job.</td>
<td>line 4n Job per pattern</td>
<td class="cite">FullProf_Manual.pdf, p. 69 · scor_rxn.pcr L1–9</td>
</tr>
<tr class="even">
<td><strong>Which phase contributes to which pattern</strong></td>
<td>A 0/1 flag per pattern says whether a phase contributes to it, e.g. a magnetic phase only in the neutron patterns.</td>
<td>phase line 19-2 JCONTR</td>
<td class="cite">FullProf_Manual.pdf, p. 88 · FullProf_Manual.pdf, p. 92</td>
</tr>
<tr class="odd">
<td><strong>Minimum d-spacing per pattern</strong></td>
<td>Uses only reflections with d above a given value for a pattern, e.g. to cut a TOF bank going far in Q.<br>
<span class="m">Since 20 January 2003.</span><br>
<span class="m">Not in the 2001 manual. The keyword moved from the phase-name line into the COMMANDS block introduced on 15 January 2005.</span></td>
<td>DLIM pat d_min: on the phase-name line (2003), in the COMMANDS block (2005 on)</td>
<td class="cite">FP_COMMANDS.pdf, p. 1 · Ho2BaCuO5_1p5K_modes.pcr · Fullprof_News_2003.htm L2709–2744 · Fullprof_News_2005.htm L1727–1737</td>
</tr>
<tr class="even">
<td><strong>ILL raw-data reduction (Get_Data, PANDA)</strong></td>
<td>Get_Data, a console program also driven from WinPLOTR-2006, extracts and reduces raw data of the ILL powder diffractometers (new D20 files, time normalisation and a global zero in 2014; NeXus files and two integration methods for the D2B detector in 2023). PANDA (Python/PySide6, O. Fabelo) shows D1B, D2B and D20 NeXus raw data and, since May 2026, .prf plots.<br>
<span class="m">Since 14 May 2013 (Get_Data); 16 March 2026 (PANDA, testing).</span><br>
<span class="m">Instrument-specific (ILL); PANDA is "in a testing stage".</span></td>
<td>external programs; toolbar Programs menu (2026)</td>
<td class="cite">FullProf_News_2013.htm L120–125 · FullProf_News_2014.htm L96–98 · FullProf_News_2023.htm L196–200 · FullProf_News_2026.htm L122–125 · FullProf_News_2026.htm L127–133 · FullProf_News_2026.htm L35–37</td>
</tr>
</tbody>
</table>
</div>
<h2 id="structure" class="anchored">The crystal structure</h2>
<div class="table-wrap">
<table class="inventory caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Capability</th>
<th data-quarto-table-cell-role="th">What it does</th>
<th data-quarto-table-cell-role="th">In the <code>.pcr</code></th>
<th data-quarto-table-cell-role="th">Sources</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Space group from its symbol</strong></td>
<td>Generates operators and reflections from a Hermann–Mauguin symbol (origin choice and rhombohedral setting in the symbol) or a Hall symbol after the keyword HALL.<br>
<span class="m">Operators and reflections come from the CrysFML Fortran 90 library (with J. González-Platas) since January 2001, replacing A. C. Larson's code; ICSD-style symbols ending in ":R" and origin choices such as "F d -3 m:1" accepted since 27 April 2022 (version 7.70).</span></td>
<td>line 22 space-group symbol; phase line Isy=0</td>
<td class="cite">FullProf_Manual.pdf, p. 90 · FullProf_Manual.pdf, p. 95 · MgAl2O4s_Set1.pcr · Fullprof_News_2001.htm L947–961 · FullProf_News_2022.htm L280–287</td>
</tr>
<tr class="even">
<td><strong>User-given symmetry operators</strong></td>
<td>Reads the operators as <span class="math inline">\(3 \times 3\)</span> matrices with translations or as SYMM x,y,z strings; the Laue class and centring are given for checking; reflections are still generated from the symbol.</td>
<td>phase line Isy=1 or -1; lines 23b–24 Nsym Cen Laue, SYMM</td>
<td class="cite">FullProf_Manual.pdf, p. 90 · FullProf_Manual.pdf, pp. 95–98 · prca_2pat.pcr</td>
</tr>
<tr class="odd">
<td><strong>Lattice parameters</strong></td>
<td>Refines a, b, c, α, β, <span class="math inline">\(\gamma\)</span>; refinement codes act on the reciprocal metric A–F of 1/d<span class="math inline">\(^{2}\)</span> = Ah<span class="math inline">\(^{2}\)</span> + Bk<span class="math inline">\(^{2}\)</span> + Cl<span class="math inline">\(^{2}\)</span> + Dkl + Ehl + Fhk, so symmetry-equal constants share a code.</td>
<td>phase cell line a b c α β <span class="math inline">\(\gamma\)</span> with codes</td>
<td class="cite">FullProf_Manual.pdf, p. 19 · FullProf_Manual.pdf, p. 112 · k2na1p5.pcr L66–68</td>
</tr>
<tr class="even">
<td><strong>Atom positions</strong></td>
<td>Fractional coordinates x, y, z of each atom in the asymmetric unit, each with its refinement code.</td>
<td>atom line (line 25) X Y Z</td>
<td class="cite">FullProf_Manual.pdf, p. 100 · Cocus_start-excl.pcr L41–44</td>
</tr>
<tr class="odd">
<td><strong>Site occupancies</strong></td>
<td>Occupancy entered as chemical occupancy × site multiplicity (or normalised to the general multiplicity); refined like any parameter, e.g. two species sharing a site with opposite codes.<br>
<span class="m">Since 22 October 2024 (version 8.10) the conversion of "convenient" occupancies to true ones assumes that the first atom alone, or all atoms on the same position, fill the site (before: the first two atoms).</span></td>
<td>atom line Occ</td>
<td class="cite">FullProf_Manual.pdf, p. 102 · MgAl2O4s_Rietveld.pcr L71–78 · FullProf_News_2024.htm L65–69</td>
</tr>
<tr class="even">
<td><strong>Isotropic displacement parameters</strong></td>
<td>One Biso (Å²) per atom.</td>
<td>atom line Biso</td>
<td class="cite">FullProf_Manual.pdf, p. 100 · FullProf_Manual.pdf, p. 102</td>
</tr>
<tr class="odd">
<td><strong>Overall displacement parameter</strong></td>
<td>One overall B per phase added to the atomic ones; used early in refinements and, in quantitative analysis, to absorb a missing absorption correction.</td>
<td>phase line 26 Bov</td>
<td class="cite">FullProf_Manual.pdf, p. 108 · FullProf_Manual.pdf, p. 14 · Exercise-EgyptianMakeupPowders.pdf, p. 1</td>
</tr>
<tr class="even">
<td><strong>Anisotropic displacement parameters</strong></td>
<td>Six β_ij per atom with site-symmetry restrictions, applied automatically in automatic mode; N_t=-2 converts Biso to β_ij; output converted to U_ij and r.m.s. displacements.<br>
<span class="m">N_t=-2 and automatic site-symmetry constraints since 8 April 2002 (version 2.10).</span></td>
<td>atom line N_t=2 (or -2), extra line beta11…beta23</td>
<td class="cite">FullProf_Manual.pdf, p. 100 · FullProf_Manual.pdf, pp. 102–103 · FullProf_Manual.pdf, p. 58 · pbso4a.pcr L42–43 · Fullprof_News_2002.htm L1226–1230 · Fullprof_News_2002.htm L1252–1257</td>
</tr>
<tr class="odd">
<td><strong>Scattering lengths and form factors</strong></td>
<td>Internal tables keyed by atom type (element for neutron b, ion such as CU+2 for X-ray f); user tables as 4-Gaussian coefficients or (sinθ/λ, f) pairs, either fitted or interpolated, or a user scattering length.</td>
<td>atom Typ; line 4 Nsc; line 12 NAM DFP DFPP ITY</td>
<td class="cite">FullProf_Manual.pdf, p. 70 · FullProf_Manual.pdf, pp. 79–81 · nabd4.pcr L4–5</td>
</tr>
<tr class="even">
<td><strong>Anomalous dispersion</strong></td>
<td>f′ and f″ given per element for each pattern, e.g. for synchrotron data near an edge.</td>
<td>line 12 DFP DFPP, ITY=2</td>
<td class="cite">FullProf_Manual.pdf, pp. 79–80 · highpress.pcr L20–26</td>
</tr>
<tr class="odd">
<td><strong>Special form factors for molecules</strong></td>
<td>Refinable form factors of whole objects for plastic crystals: spherical shell, sphere, ellipsoid, disk, symmetry-adapted spherical (or cubic) harmonics, and four user dummies.<br>
<span class="m">The manual marks N_t=4 "under test!" (p. 102). Symmetry-adapted spherical harmonics completed with the C60 example in January 2001; SASH normalisation divided by √(4π) so that a free rotator matches SPHS (April 2002); N_t=5 adds anisotropic β_ij to these objects (February 2005).</span></td>
<td>atom Typ SPHS, SPHE, SASH, ELLI, DISK, FUD1–4; N_t=4</td>
<td class="cite">FullProf_Manual.pdf, p. 6 · FullProf_Manual.pdf, pp. 101–104 · c60.pcr L27 · c60.pcr L34 · Fullprof_News_2001.htm L1219–1236 · Fullprof_News_2002.htm L1016–1057 · Fullprof_News_2005.htm L1546–1556</td>
</tr>
<tr class="even">
<td><strong>Subset of operators per atom</strong></td>
<td>Applies only operators In…Fin to an atom, for pseudo-symmetric descriptions; the manual warns about reflection multiplicities.</td>
<td>atom line In Fin</td>
<td class="cite">FullProf_Manual.pdf, p. 102</td>
</tr>
<tr class="odd">
<td><strong>Reflections read instead of generated</strong></td>
<td>Reads h, k, l, multiplicity (and an optional per-reflection coefficient) for a phase from CODFILn.hkl instead of generating them from the space group.</td>
<td>phase line Irf=1</td>
<td class="cite">FullProf_Manual.pdf, p. 92 · FullProf_Manual.pdf, p. 137</td>
</tr>
<tr class="even">
<td><strong>Fixed partial structure factor</strong></td>
<td>Adds a constant complex structure factor read per reflection to the calculated one, e.g. a rigid host in intercalation compounds.</td>
<td>phase line Irf=3 (or -4 with integrated intensities)</td>
<td class="cite">FullProf_Manual.pdf, p. 92 · FullProf_Manual.pdf, p. 139</td>
</tr>
<tr class="odd">
<td><strong>Symmetry-mode parametrisation</strong></td>
<td>Refines a distorted structure through the amplitudes (Å) of symmetry-adapted displacement modes of a parent structure instead of x, y, z: polarisation vectors V_MODES and amplitudes A_MODES, templates written by AMPLIMODES (Bilbao); amplitudes take codes, so they can be constrained, and Max_Amplitude caps them.<br>
<span class="m">Since 29 August 2008 (version 4.40).</span><br>
<span class="m">Not in the 2001 manual. Max_Amplitude on all amplitudes since January 2009, global amplitudes per irrep in .out and .sum since September 2009; CIF of the conventional structure with esd's since May 2011; occupational modes and ISODISTORT .pcr files run directly since November 2017.</span></td>
<td>phase line Jbt=6; V_MODES, A_MODES blocks after the atoms</td>
<td class="cite">FullProf-Tutorial-Symmetry-Modes.pdf, pp. 3–6 · LMO_Modes_Pbnm.pcr L58–80 · Fullprof_News_2008.htm L86–172 · Fullprof_News_2009.htm L56–57 · Fullprof_News_2009.htm L395–414 · FullProf_News_2011.htm L225–226 · FullProf_News_2017.htm L50–55</td>
</tr>
<tr class="even">
<td><strong>Bond distances, angles and bond-valence sums</strong></td>
<td>Lists distances and angles up to set limits and computes bond-valence sums for declared cations and anions (tolerance 20 % by default), with a global instability index.</td>
<td>phase line Jdi=3 or 4; lines 20–21 DIS_MAX ANG_MAX BVS, ions</td>
<td class="cite">FullProf_Manual.pdf, p. 92 · FullProf_Manual.pdf, pp. 94–95 · Tutorial-Y2O3.pdf, p. 21</td>
</tr>
</tbody>
</table>
</div>
<h2 id="profile" class="anchored">Peak shapes, instrument and peak positions</h2>
<div class="table-wrap">
<table class="inventory caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Capability</th>
<th data-quarto-table-cell-role="th">What it does</th>
<th data-quarto-table-cell-role="th">In the <code>.pcr</code></th>
<th data-quarto-table-cell-role="th">Sources</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Gaussian and Lorentzian profiles</strong></td>
<td>Normalised Gaussian, Lorentzian (Cauchy) and two modified Lorentzians (power 2 and 3/2).</td>
<td>line 4 Npr=0, 1, 2, 3 (or phase Npr)</td>
<td class="cite">FullProf_Manual.pdf, p. 69 · FullProf_Manual.pdf, p. 47</td>
</tr>
<tr class="even">
<td><strong>Pseudo-Voigt</strong></td>
<td>pV = ηL + (1−η)G with η = η0 + X·2<span class="math inline">\(\theta\)</span> (η0 = Shape1); recommended for CW data, mostly Lorentzian for X-rays, Gaussian for neutrons.</td>
<td>Npr=5; phase line 26 Shape1, line 27 X</td>
<td class="cite">FullProf_Manual.pdf, pp. 48–50 · FullProf_Manual.pdf, p. 15 · Cocuc_LeBail.pcr L4–5</td>
</tr>
<tr class="odd">
<td><strong>Pearson VII</strong></td>
<td>Pearson VII with exponent m = m0 + 100X/2<span class="math inline">\(\theta\)</span> + 10000Y/(2<span class="math inline">\(\theta\)</span>)².<br>
<span class="m">Lowest accepted exponent m = 0.6 since 16 February 2004.</span></td>
<td>Npr=6; Shape1 = m0</td>
<td class="cite">FullProf_Manual.pdf, p. 47 · FullProf_Manual.pdf, p. 49 · Fullprof_News_2004.htm L4449–4454</td>
</tr>
<tr class="even">
<td><strong>Thompson–Cox–Hastings pseudo-Voigt with axial divergence</strong></td>
<td>Pseudo-Voigt whose η and FWHM follow from separate Gaussian and Lorentzian widths (TCH), convoluted with the Finger–Cox–Jephcoat axial-divergence asymmetry from S_L and D_L (source and detector width over distance); the basis of the size-strain analysis.<br>
<span class="m">Since 9 January 2001 (version 1.8a: Finger axial divergence added to Npr=7).</span><br>
<span class="m">Profiles are normalised to unit area; the TCH relations between H, H_G, H_L and η are in Microstructural_effects.pdf. The axial-divergence refinement was updated after Hester (J. Appl. Cryst. 46, 1219, 2013); S_L ≠ 0 with D_L = 0 is recommended to remove the S_L/D_L correlation (July 2019).</span></td>
<td>Npr=7; line 30 S_L D_L</td>
<td class="cite">FullProf_Manual.pdf, p. 69 · FullProf_Manual.pdf, pp. 48–49 · FullProf_Manual.pdf, pp. 112–113 · Cocus-asym.pcr L72–74 · Fullprof_News_2001.htm L1025–1031 · Microstructural_effects.pdf, pp. 1–3 · FullProf_News_2013.htm L105–106 · FullProf_News_2019.htm L153–156</td>
</tr>
<tr class="odd">
<td><strong>Pseudo-Voigt with axial divergence</strong></td>
<td>Pseudo-Voigt convoluted with the Finger axial-divergence function, applied below AsymLim.</td>
<td>Npr=12</td>
<td class="cite">FullProf_Manual.pdf, p. 69 · FullProf_Manual.pdf, p. 113 · gabriela.pcr L7–11</td>
</tr>
<tr class="even">
<td><strong>TCH pseudo-Voigt for TOF</strong></td>
<td>The TCH Voigt (Npr=7) used for TOF patterns: symmetric, without rise and decay exponentials, with the TOF, <span class="math inline">\(\sigma\)</span> and <span class="math inline">\(\gamma\)</span> d-dependences of Npr=9; for long-pulse instruments with chopper peak shaping, or samples whose broadening clearly exceeds the instrumental one.<br>
<span class="m">Since 10 January 2021 (version 7.40).</span></td>
<td>Npr=7 with Job=-1</td>
<td class="cite">FullProf_News_2021.htm L234–240</td>
</tr>
<tr class="odd">
<td><strong>Tripled pseudo-Voigt</strong></td>
<td>Sum of three pseudo-Voigts displaced by ±D = Sh1/(d cosθ), weights X, 1−X−Y, Y; for medium-resolution neutron instruments with monochromator defects.</td>
<td>Npr=4; line 33 SHP1 SHP2</td>
<td class="cite">FullProf_Manual.pdf, pp. 49–50 · FullProf_Manual.pdf, p. 109</td>
</tr>
<tr class="even">
<td><strong>Split pseudo-Voigt</strong></td>
<td>Separate U, V, W, η0, X for the left and right halves of the peak, with extra Shp1/tan<span class="math inline">\(^{2}\)</span>2<span class="math inline">\(\theta\)</span> (left, 2<span class="math inline">\(\theta\)</span> &lt; 90°) and Shp2/tan<span class="math inline">\(^{2}\)</span>2<span class="math inline">\(\theta\)</span> (right) terms.</td>
<td>Npr=11; second profile set Ur Vr Wr Eta0r Xr</td>
<td class="cite">FullProf_Manual.pdf, p. 50 · FullProf_Manual.pdf, pp. 109–111</td>
</tr>
<tr class="odd">
<td><strong>Numerical peak shape</strong></td>
<td>A tabulated profile P(x) with its derivative, normalised to FWHM 1 and unit area, given at several 2<span class="math inline">\(\theta\)</span> and interpolated, for instruments the analytical functions do not fit.<br>
<span class="m">Up to 16 numerical profiles, and interpolation between two profiles corrected, on 29 April 2002.</span></td>
<td>Npr=8; file CODFIL.shp or GLOBAL.shp</td>
<td class="cite">FullProf_Manual.pdf, p. 69 · FullProf_Manual.pdf, p. 130 · FullProf_Manual.pdf, p. 9 · Fullprof_News_2002.htm L867–871 · Fullprof_News_2002.htm L929–932</td>
</tr>
<tr class="even">
<td><strong>TOF back-to-back exponentials ⊗ pseudo-Voigt</strong></td>
<td>TOF profile: pseudo-Voigt convoluted with rising and decaying exponentials (GSAS TOF function 4 except the size–strain models), α = α0 + α1/d, β = β0 + β1/d<span class="math inline">\(^{4}\)</span>; Gaussian variance <span class="math inline">\(\sigma\)</span>² = (Sig2 + GSIZ)d<span class="math inline">\(^{4}\)</span> + (Sig1 + DST)d<span class="math inline">\(^{2}\)</span> + Sig0 and Lorentzian <span class="math inline">\(\gamma\)</span> = (gam2 + DSIZ)d<span class="math inline">\(^{2}\)</span> + (gam1 + LStr)d + gam0.<br>
<span class="m">Closed form (erfc and exponential integral E1) in TOF_FullProf.pdf (Dec. 2003), after the June 2003 reorganisation made instrumental refinement stable. Since 10 January 2021 (version 7.40, POWGEN) extra terms sig_q, α_q/√d and β_q/d<span class="math inline">\(^{2}\)</span> (sig_q·d since July 2024); the News warns they are strongly correlated: fit them on a standard, then refine only size and strain.</span></td>
<td>Npr=9; line 27 Sig-2 Sig-1 Sig-0…, Gam-2 Gam-1 Gam-0; line 30 alph0 beta0 alpha1 beta1</td>
<td class="cite">FullProf_Manual.pdf, p. 69 · FullProf_Manual.pdf, p. 109 · FullProf_Manual.pdf, pp. 111–112 · CeO2_PEARL.pcr L1–5 · TOF_FullProf.pdf, pp. 1–3 · Fullprof_News_2003.htm L1339–1348 · FullProf_News_2021.htm L173–208 · FullProf_News_2024.htm L136–138</td>
</tr>
<tr class="odd">
<td><strong>TOF epithermal/thermal crossover</strong></td>
<td>Same profile with Hodges' two-regime TOF–d relation: epithermal TOFe = Zero + Dtt1·d, thermal TOFt = Zerot + Dtt1t·d − Dtt2t/d, mixed by n = ½ erfc(Width·(x-cross − 1/d)); rise and decay mixed the same way, 1/α = nα^e + (1−n)α^t with α^e = α0e + α1e·d, α^t = α0t − α1t/d (likewise β, constants in μs).<br>
<span class="m">Since 9 January 2001 (version 1.8a).</span><br>
<span class="m">Expressions by J. Hodges (unpublished) from GPPD (Argonne) data; IRF support as Res=6 since January 2003.</span></td>
<td>Npr=10; Zerot Dtt1t Dtt2t x-cross Width</td>
<td class="cite">FullProf_Manual.pdf, pp. 84–85 · FullProf_Manual.pdf, pp. 112–113 · gabriela.pcr L74–75 · Fullprof_News_2001.htm L1095–1099 · TOF_FullProf.pdf, pp. 3–4</td>
</tr>
<tr class="even">
<td><strong>TOF Ikeda–Carpenter</strong></td>
<td>TCH pseudo-Voigt convoluted with the Ikeda–Carpenter moderator pulse I(t) = S(t) ⊗ R(t), S = (α³/2)t<span class="math inline">\(^{2}\)</span>e^(−αt), R = (1−R)δ(t) + Rβe^(−βt), with α = 1/(α0 + λα1), β = 1/β0, R = exp(−81.799/(κλ²)); refinable alph0, alph1, beta0, kappa, widths as for Npr=9.<br>
<span class="m">Since 10 June 2003 ("now working").</span><br>
<span class="m">Subroutine by L. Chapon, with the GSAS simplification (k = 0.05). Zero, Dtt1 and Dtt2 differ from Npr=9, whose peak position is the rising edge. No test in FP_tests uses it.</span></td>
<td>Npr=13; in a Res=5 IRF kappa takes the place of beta1</td>
<td class="cite">FullProf_Manual.pdf, p. 69 · TOF_FullProf.pdf, p. 1 · TOF_FullProf.pdf, pp. 4–5 · TOF_FullProf.pdf, p. 6 · Fullprof_News_2003.htm L1339–1348 · Fullprof_News_2004.htm L4690–4700</td>
</tr>
<tr class="odd">
<td><strong>Peak-shape choice per phase</strong></td>
<td>Each phase may use its own profile function; 0 takes the pattern default.</td>
<td>phase line Npr (multi-pattern: line 19-3 Irf Npr Jtyp)</td>
<td class="cite">FullProf_Manual.pdf, p. 69 · FullProf_Manual.pdf, p. 93</td>
</tr>
<tr class="even">
<td><strong>Angular dependence of the width (CW)</strong></td>
<td>H<span class="math inline">\(^{2}\)</span> = (U + D_ST<span class="math inline">\(^{2}\)</span>)tan<span class="math inline">\(^{2}\)</span><span class="math inline">\(\theta\)</span> + V tanθ + W + IG/cos<span class="math inline">\(^{2}\)</span><span class="math inline">\(\theta\)</span> (Caglioti plus strain and Gaussian size terms), in (degrees 2<span class="math inline">\(\theta\)</span>)²; for TCH separate Gaussian and Lorentzian widths, H_L = X tanθ + (Y + F)/cosθ.</td>
<td>phase line 27 U V W X Y GauSiz LorSiz</td>
<td class="cite">FullProf_Manual.pdf, pp. 49–50 · FullProf_Manual.pdf, pp. 108–109 · pdfinal.pcr L59–64</td>
</tr>
<tr class="odd">
<td><strong>Separate widths for λ2</strong></td>
<td>U2, V2, W2 for the second wavelength when Ratio is given negative.</td>
<td>line 8 Ratio&lt;0; line 32 U2 V2 W2</td>
<td class="cite">FullProf_Manual.pdf, p. 76 · FullProf_Manual.pdf, p. 109 · ce.pcr L10–11</td>
</tr>
<tr class="even">
<td><strong>Empirical peak asymmetry</strong></td>
<td>Multiplicative correction As(z) = 1 + (P1·Fa + P2·Fb)/tanθ + (P3·Fa + P4·Fb)/tan2<span class="math inline">\(\theta\)</span>, applied to peaks below AsymLim; P1, P2 usually suffice for neutrons.</td>
<td>line 30 Asy1–Asy4; line 8 AsyLim</td>
<td class="cite">FullProf_Manual.pdf, p. 54 · FullProf_Manual.pdf, p. 76 · FullProf_Manual.pdf, p. 112 · Cocus-firstpeak.pcr L65–67</td>
</tr>
<tr class="odd">
<td><strong>Howard asymmetry</strong></td>
<td>Asymmetry by Howard's method: five pseudo-Voigts at displaced points combined by Bode's rule; only for Npr=5 and 7.<br>
<span class="m">Removed before the July 2001 manual went out: the News of 9 January 2001 (version 1.8a) says this option, selected by a negative number of phases, "HAS BEEN SUPPRESSED" because the other asymmetry corrections are better. Not in the tutorials or tests.</span></td>
<td>a negative number of phases (Nph&lt;0), as the manual writes it</td>
<td class="cite">FullProf_Manual.pdf, p. 54 · Fullprof_News_2001.htm L1207–1211</td>
</tr>
<tr class="even">
<td><strong>Profile cut-off</strong></td>
<td>Each peak is computed over Wdt × FWHM on each side: about 4 for Gaussian, 20–30 for Lorentzian, 4–5 for TOF.</td>
<td>line 8 Wdt</td>
<td class="cite">FullProf_Manual.pdf, p. 75 · FullProf_Manual.pdf, p. 15</td>
</tr>
<tr class="odd">
<td><strong>Instrumental resolution file (CW)</strong></td>
<td>Describes the instrument's Gaussian and Lorentzian widths (U, V, W, X, Y, Z per wavelength, three functional forms) or a table of up to 60 (2<span class="math inline">\(\theta\)</span>, H_G, H_L) points; with it, refined widths are the sample's, and the .mic size-strain file is written. Built by refining a standard such as LaB6.<br>
<span class="m">Usable with profiles other than Npr=7 since 14 May 2002, the keywords JOBT, WAVE, PROF and ASYM overriding the .pcr; EdPCR writes IRF templates and an IRF folder of instruments is installed (2003–2004); IRF values take priority over the .pcr and the GEOM geometry is written in the .out since October 2023.</span></td>
<td>line 4 Res=1–4; line 6 IRF file name; IRF keywords JOBT, WAVE, PROF, ASYM, GEOM</td>
<td class="cite">FullProf_Manual.pdf, p. 70 · FullProf_Manual.pdf, pp. 131–132 · LaB6a.irf L1–14 · ybfluo_pm_IRF.pcr L4–6 · Fullprof_News_2002.htm L658–846 · Fullprof_News_2003.htm L1443–1449 · Fullprof_News_2004.htm L4885–4891 · FullProf_News_2023.htm L40–45</td>
</tr>
<tr class="even">
<td><strong>Instrumental resolution from pseudo-Voigt parameters (Res=-1)</strong></td>
<td>The IRF gives U, V, W, η, X, Y of an instrumental pseudo-Voigt; for each reflection the Gaussian and Lorentzian parts of the equivalent Voigt (de Keijser 1982) are added, quadratically and linearly, to the sample widths of the TCH pseudo-Voigt (Npr=7).<br>
<span class="m">Since 20 January 2003.</span></td>
<td>line 4 Res=-1; IRF line U V W ETA X Y</td>
<td class="cite">Fullprof_News_2003.htm L2358–2447</td>
</tr>
<tr class="odd">
<td><strong>Tabulated resolution with axial divergence (Res=8)</strong></td>
<td>Like the Res=4 table of (2<span class="math inline">\(\theta\)</span>, H_G, H_L) points, but each line also carries the Finger axial-divergence parameters S_L and D_L, so asymmetry can vary across the pattern; Res=4 files may start with WAVE λ1 λ2 ratio.<br>
<span class="m">Since 10 February 2004.</span></td>
<td>line 4 Res=8; IRF lines 2<span class="math inline">\(\theta\)</span> H_G H_L S_L D_L</td>
<td class="cite">Fullprof_News_2004.htm L4632–4637 · Fullprof_News_2004.htm L4669–4683</td>
</tr>
<tr class="even">
<td><strong>TOF resolution file (Res=5, 6)</strong></td>
<td>Keyword IRF per TOF bank: D2TOF (or ZD2TOF with the zero), TWOTH, SIGMA, GAMMA, ALFBE, and for Npr=10 also D2TOT and ALFBT; except the bank angle, the values are added to the refinable .pcr ones, so with a good IRF the .pcr refines only shifts, size and strain. Several banks in one file are separated by END.<br>
<span class="m">Since 20 January 2003.</span><br>
<span class="m">Not in the 2001 manual, which says the IRF works for constant wavelength only (p. 70). The meaning of Res=5 has not changed: it was always this keyword file (the FP_tests file respol.irf is one); the interpolated tables FP_COMMANDS refers to were added inside it from 2005 (next entry). ZD2TOF, ZD2TOT give the zero in the IRF since April 2011; the 2003 TOF document did not accept it.</span></td>
<td>line 4n Res=5 (Npr=9, 13) or Res=6 (Npr=10); keywords NPROF, TOFRG, D2TOF, TWOTH, SIGMA, GAMMA, ALFBE, D2TOT, ALFBT</td>
<td class="cite">respol.irf L1–15 · test.pcr L6–8 · Fullprof_News_2003.htm L2454–2606 · Fullprof_News_2003.htm L284–302 · TOF_FullProf.pdf, p. 1 · TOF_FullProf.pdf, pp. 6–7 · Fullprof_News_2004.htm L4690–4715 · FullProf_News_2011.htm L254–263</td>
</tr>
<tr class="odd">
<td><strong>TOF lookup tables (interpolated Res=5 file)</strong></td>
<td>Inside a Res=5 IRF, tables versus d of α and β, of <span class="math inline">\(\sigma\)</span>² and <span class="math inline">\(\gamma\)</span>, of the peak shift, or of all five, interpolated linearly for each reflection, for moderators the analytical laws do not describe; refined .pcr shifts are still added. Generate_new_IRF in COMMANDS makes FullProf write such .irf files after a refinement.<br>
<span class="m">Since 12 December 2005 (LISTALFBET); 25 October 2009, version 4.70 (<span class="math inline">\(\sigma\)</span>², <span class="math inline">\(\gamma\)</span>); 18 April 2011 (shift).</span><br>
<span class="m">Announced "in the near future" in the Dec. 2003 TOF document. Up to 100 points in 2005, fewer than 400 from 2009; without an IRF FullProf writes TOF_irf_file.irf for reuse. The January 2021 News calls it "probably the most precise" TOF option.</span></td>
<td>Res=5 IRF keywords LISTALFBET, LISTSIGGAM, LIST_SIG_GAM_ALF_BET, LIST_SHIFT, LIST_SIG_GAM_ALF_BET_SHIFT; COMMANDS Generate_new_IRF</td>
<td class="cite">TOF_FullProf.pdf, p. 7 · Fullprof_News_2005.htm L423–444 · Fullprof_News_2005.htm L602–606 · Fullprof_News_2009.htm L22–48 · FullProf_News_2011.htm L265–281 · FullProf_News_2021.htm L210–229 · FP_COMMANDS.pdf, p. 12</td>
</tr>
<tr class="even">
<td><strong>TOF_fit_LM</strong></td>
<td>Console program that refines limited ranges of TOF patterns and writes .irf files to be merged into one interpolated Res=5 file; since December 2021 also by orthogonal distance regression (ODRPACK95, Levenberg–Marquardt with box constraints); WinPLOTR reads its .xrf results.<br>
<span class="m">Since 10 January 2021 (version 7.40).</span></td>
<td>external console program; output .irf, .xrf</td>
<td class="cite">FullProf_News_2021.htm L217–221 · FullProf_News_2021.htm L20–27</td>
</tr>
<tr class="odd">
<td><strong>Zero shift</strong></td>
<td>Refinable zero of the scattering variable, T_true = T_exp − Zero (2<span class="math inline">\(\theta\)</span>, TOF or energy).</td>
<td>line 14 Zero</td>
<td class="cite">FullProf_Manual.pdf, pp. 82–83 · Cocus-firstpeak.pcr L22–23</td>
</tr>
<tr class="even">
<td><strong>Sample displacement and transparency</strong></td>
<td>Shifts ∝ cosθ (Bragg–Brentano displacement, SyCos = −2s/R; Debye–Scherrer eccentricity) and ∝ sin2<span class="math inline">\(\theta\)</span> (transparency of thick samples, SySin = 1/(2μR)); curved-PSD flat-plate displacement too.<br>
<span class="m">The thin-sample transparency correction "is not implemented in FullProf" (p. 56). The meanings were fixed on 19 July 2011 (version 5.20): for Debye–Scherrer geometry (CW neutrons Ilo=0, synchrotron Ilo=3, laboratory X-rays Ilo=-2) shift = SyCos·cos2<span class="math inline">\(\theta\)</span> + SySin·sin2<span class="math inline">\(\theta\)</span>; for Bragg–Brentano X-rays SyCos·cosθ (displacement) + SySin·sin2<span class="math inline">\(\theta\)</span> (transparency).</span></td>
<td>line 14 SyCos SySin</td>
<td class="cite">FullProf_Manual.pdf, pp. 56–57 · FullProf_Manual.pdf, p. 83 · Cocus-firstpeak.pcr L22–23 · FullProf_News_2011.htm L67–94</td>
</tr>
<tr class="odd">
<td><strong>Wavelength refinement</strong></td>
<td>Refines the wavelength; the cell must then be fixed. With two wavelengths the first can be refined without forcing the second to equal it (since July 2024).</td>
<td>line 14 Lambda with code</td>
<td class="cite">FullProf_Manual.pdf, p. 83 · FullProf_News_2024.htm L144–146</td>
</tr>
<tr class="even">
<td><strong>Phase-dependent shifts</strong></td>
<td>Zero, SyCos and SySin per phase and per pattern (Zero_ph, SyCos_ph, SySin_ph) for Bragg–Brentano and Debye–Scherrer constant-wavelength data: phases off the optical centre, multilayer films, two windows of an operando cell.<br>
<span class="m">Since 7 April 2004.</span><br>
<span class="m">Not in the 2001 manual.</span></td>
<td>phase line Ph_Shift=1 after Nsp_Ref (More=1)</td>
<td class="cite">Exercise-NMC111.pdf, pp. 2–3 · Ca2MnO4_300k.pcr L44 · Fullprof_News_2004.htm L3098 · Fullprof_News_2004.htm L3117–3154</td>
</tr>
</tbody>
</table>
</div>
<h2 id="background" class="anchored">Background</h2>
<div class="table-wrap">
<table class="inventory caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Capability</th>
<th data-quarto-table-cell-role="th">What it does</th>
<th data-quarto-table-cell-role="th">In the <code>.pcr</code></th>
<th data-quarto-table-cell-role="th">Sources</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Polynomial background</strong></td>
<td>Refinable polynomial in (T/Bkpos − 1) about a user origin Bkpos: 6 coefficients, or 12 with the extra line.<br>
<span class="m">For constant wavelength the last three of the 12 coefficients (Nba=-3) are inverse powers of 2<span class="math inline">\(\theta\)</span> (July 2003).</span></td>
<td>Nba=0 (6 terms), Nba=-3 (12 terms); line 8 Bkpos; line 17 BACK1…</td>
<td class="cite">FullProf_Manual.pdf, pp. 45–46 · FullProf_Manual.pdf, pp. 85–86 · Cocuc_LeBail.pcr L24–26 · Fullprof_News_2003.htm L888–963</td>
</tr>
<tr class="even">
<td><strong>Debye-like terms</strong></td>
<td>Adds six terms BC_j sin(Q r_j)/(Q r_j) with refinable distances r_j (Å) to the polynomial, for amorphous or liquid-like contributions.</td>
<td>Nba=-1; Bc1–Bc6, D1–D6</td>
<td class="cite">FullProf_Manual.pdf, pp. 45–46 · FullProf_Manual.pdf, p. 86 · nac_3t2.pcr L25</td>
</tr>
<tr class="odd">
<td><strong>Interpolated background points</strong></td>
<td>Linear interpolation between N user points, fixed or with refinable heights.<br>
<span class="m">Heights refinable with a code beside each value since 21 May 2001 (version 1.9c); codes forced to 0 inside excluded regions.</span></td>
<td>Nba=N<span class="math inline">\(\ge 2\)</span>; line 10 POS BCK with codes</td>
<td class="cite">FullProf_Manual.pdf, p. 46 · FullProf_Manual.pdf, p. 78 · la0.pcr L16–46 · Fullprof_News_2001.htm L468–476</td>
</tr>
<tr class="even">
<td><strong>Cubic-spline background</strong></td>
<td>Interpolation through the user points by cubic splines.<br>
<span class="m">Later versions reuse Nba=-4 and -5 for Fourier and Chebyshev series (below).</span></td>
<td>Nba&lt;-4 (as the 2001 manual states)</td>
<td class="cite">FullProf_Manual.pdf, p. 69 · FullProf_Manual.pdf, p. 78</td>
</tr>
<tr class="odd">
<td><strong>Fourier cosine background</strong></td>
<td>12-term cosine series Σ B_j cos(j T/C), C = 180/π for 2<span class="math inline">\(\theta\)</span>, Tmax for TOF or energy; later up to 18 terms.<br>
<span class="m">Since 13 May 2001; 18 terms since 10 December 2008.</span><br>
<span class="m">The 2001 manual gives the formula but no Nba value; the News gives Nba=-4.</span></td>
<td>Nba=-4, coefficients where Nba=-3 puts them</td>
<td class="cite">FullProf_Manual.pdf, pp. 45–46 · arg_si.pcr L25 · Fullprof_News_2001.htm L513–554 · Fullprof_News_2008.htm L19–21</td>
</tr>
<tr class="even">
<td><strong>Chebyshev background</strong></td>
<td>Chebyshev polynomial series, up to 24 coefficients, entered where the Fourier coefficients go; the first is the average level.<br>
<span class="m">Since 17 June 2011.</span><br>
<span class="m">Not in the 2001 manual. The News calls it "by far the most stable way of refining background parameters"; EdPCR accepts it since October 2017.</span></td>
<td>Nba=-5</td>
<td class="cite">pbso4_cheb.pcr L26 · Cocus-asym.pcr L25–33 · FullProf_News_2011.htm L129–137 · FullProf_News_2017.htm L131–132</td>
</tr>
<tr class="odd">
<td><strong>Background from a file</strong></td>
<td>Reads a background curve and adjusts it as b1·Backg[(1+b3)2<span class="math inline">\(\theta\)</span> + b4] + b2, with |b3| <span class="math inline">\(\le 0.1\)</span> and |b4| &lt; 3° enforced; for sample-environment backgrounds.</td>
<td>Nba=1; FILE.bac; line 17 BACK1–4</td>
<td class="cite">FullProf_Manual.pdf, p. 46 · FullProf_Manual.pdf, p. 86 · FullProf_Manual.pdf, p. 8</td>
</tr>
<tr class="even">
<td><strong>Fourier-filtered background</strong></td>
<td>Updates the background every cycle by adding a strongly smoothed yobs − ycalc (window FWINDOW, at least five times a peak base); starts from and rewrites FILE.bac; the manual warns it can eat into peaks.<br>
<span class="m">Since 13 June 2023 FWINDOW is at least Npoints/6 (raised automatically), because small windows let the background follow high-frequency oscillations, and win_cyc applies the filter only on every win_cyc-th cycle.</span></td>
<td>Nba=-2; line 17 FWINDOW (win_cyc since 2023)</td>
<td class="cite">FullProf_Manual.pdf, p. 46 · FullProf_Manual.pdf, pp. 85–86 · FullProf_News_2023.htm L109–139</td>
</tr>
<tr class="odd">
<td><strong>Background profiles from files (linear combination)</strong></td>
<td>Adds to any background function up to 10 previously calculated profiles (thermal diffuse scattering, a complicated sample-environment background) read from .bac files with the same points as the data, each with a refinable coefficient.<br>
<span class="m">Since 28 July 2003 (version 2.45).</span><br>
<span class="m">Files filedat_n.bac by default, free names since July 2006, x, y, <span class="math inline">\(\sigma\)</span> (Ins=10) files since May 2011; the add_back keyword since June 2011.</span></td>
<td>MORE=2 (3 with microabsorption) on the Zero line; coefficients and codes; optional 'Codes' line of file names; VARY add_back</td>
<td class="cite">Fullprof_News_2003.htm L1097–1154 · Fullprof_News_2003.htm L1233–1236 · Fullprof_News_2006.htm L205–232 · FullProf_News_2011.htm L239–241 · FullProf_News_2011.htm L168–169</td>
</tr>
<tr class="even">
<td><strong>Peaks of foreign origin as a phase</strong></td>
<td>A parasitic peak (vanadium screens of a cryostat) modelled as a phase with fixed relative intensities read from an .hkl file and a refined scale.<br>
<span class="m">Not in the 2001 manual as a background method; built from the documented Jbt=3. TOF_FullProf.pdf (Dec. 2003) treats the Cd of the sample holder this way in the OSIRIS NAC example, because texture prevents a structure-factor calculation.</span></td>
<td>extra phase Jbt=3, Irf=2</td>
<td class="cite">HoBaCuO-HT.pcr L216–225 · TOF_FullProf.pdf, p. 9</td>
</tr>
<tr class="odd">
<td><strong>Automatic background points (FullProfAPP)</strong></td>
<td>Background points extracted by asymmetric least squares (Eilers and Boelens 2005, as in PRISMA) with log_lambda and log_p sliders for all checked patterns; editable on the plot and exportable as x, y.<br>
<span class="m">FullProfAPP manual v1.3.3 (June 2025).</span></td>
<td>FullProfAPP: Pattern &gt; Automatic Background; API calculate_background_asls</td>
<td class="cite">index.html L242–246 · index.html L367–373 · index.html L137–146 · calculators.html L131–149</td>
</tr>
<tr class="even">
<td><strong>Conversion between background types (FullProfAPP)</strong></td>
<td>Switches a .pcr between interpolated points, a Chebyshev series fitted to the points (given order) and Fourier filtering (window <span class="math inline">\(\ge\)</span> Npoints/6, applied every N cycles); a Chebyshev background goes back to 30 points, a Fourier-filtered one only by reloading points.<br>
<span class="m">Since 1 December 2023 (FullProfAPP 1.2.7, Fourier filtering).</span></td>
<td>FullProfAPP: protocol Background combo; API PcrIO.transform_*</td>
<td class="cite">index.html L632–665 · app_io.html L1767–1891 · index.html L245–255</td>
</tr>
</tbody>
</table>
</div>
<h2 id="microstructure" class="anchored">Size and strain broadening</h2>
<div class="table-wrap">
<table class="inventory caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Capability</th>
<th data-quarto-table-cell-role="th">What it does</th>
<th data-quarto-table-cell-role="th">In the <code>.pcr</code></th>
<th data-quarto-table-cell-role="th">Sources</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Isotropic size and strain</strong></td>
<td>With an IRF, sample broadening enters the TCH widths: U, X (and the anisotropic D_ST) are strain, Y, IG (GauSiz) and F are size, with V = W = 0; integral breadths give volume-averaged apparent size and strain per reflection, without physical model.<br>
<span class="m">The .mic microstructure output works for constant wavelength only (p. 21). Definitions (H_G<span class="math inline">\(^{2}\)</span> and H_L with the Lorentzian strain share ξ, apparent size λ/(β cosθ), strain ½βd) in Microstructural_effects.pdf.</span></td>
<td>Npr=7, Res≠0; line 27 U X Y GauSiz</td>
<td class="cite">FullProf_Manual.pdf, pp. 20–21 · FullProf_Manual.pdf, p. 111 · Microstructural_effects_FP.pdf, p. 4 · ybfluo_pm_IRF.pcr L55–57 · Microstructural_effects.pdf, pp. 3–4</td>
</tr>
<tr class="even">
<td><strong>Anisotropic strain, quartic form</strong></td>
<td>Strain broadening D_ST<span class="math inline">\(^{2}\)</span> from a quartic form in h, k, l, Σ S_HKL h^H k^K l^L, interpreted as fluctuations of the metric (Rodríguez-Carvajal 1991) in Stephens' notation; up to 15 parameters (triclinic), restricted by the Laue class.<br>
<span class="m">Stephens' notation the default (Str=1, Strain-Model = Laue class) since January 2001 (version 1.8a); D_ST<span class="math inline">\(^{2}\)</span> from the variance–covariance of the metric A–F in Microstructural_effects.pdf, with Nd2NiO4 as example.</span></td>
<td>phase line Str=1; Strain-Model = Laue class; line 37 S_400…</td>
<td class="cite">FullProf_Manual.pdf, pp. 21–22 · FullProf_Manual.pdf, pp. 119–121 · NdNi_LTOa.pcr L74–78 · Fullprof_News_2001.htm L1054–1060 · Microstructural_effects.pdf, pp. 5–6</td>
</tr>
<tr class="odd">
<td><strong>Lorentzian share of the strain</strong></td>
<td>Mixing parameter ξ splits the anisotropic strain between the Gaussian and Lorentzian widths.</td>
<td>line 38 XI</td>
<td class="cite">FullProf_Manual.pdf, p. 21 · FullProf_Manual.pdf, pp. 120–121 · NdNi_LTOa.pcr L77–78</td>
</tr>
<tr class="even">
<td><strong>Anisotropic strain, spherical harmonics</strong></td>
<td>Strain broadening as a spherical-harmonic expansion (cubic harmonics for m3 and m3m), z along the principal axis, one coefficient set per Laue class (e.g. 9 for 2/m, 4 for m3m), plus a Lorentzian-share coefficient.<br>
<span class="m">Since 24 May 2006.</span></td>
<td>phase line Str=4, Strain-Model = Laue-class number; Y_lm lines with codes</td>
<td class="cite">Fullprof_News_2006.htm L340–403</td>
</tr>
<tr class="odd">
<td><strong>Phenomenological strain models</strong></td>
<td>Eleven named strain rules with up to three parameters (Str1–3): tetragonal–orthorhombic, along a, along diagonals, correlated a/b, uniaxial along a vector, hexagonal, LaNi5-type, orthorhombic (6), monoclinic (8).</td>
<td>phase line 26 Str1 Str2 Str3 Strain-Model (Str=0)</td>
<td class="cite">FullProf_Manual.pdf, pp. 28–30 · FullProf_Manual.pdf, p. 110 · NdNi_LTOb.pcr L62–64</td>
</tr>
<tr class="even">
<td><strong>Generalised strain from cell correlations</strong></td>
<td>Ten parameters as the spreads and correlations (sines of angles, kept in [−1, 1]) of the direct cell parameters; lowest symmetry monoclinic.</td>
<td>Str=1 with Strain-Model 0, or Str=3; STR4–STR15</td>
<td class="cite">FullProf_Manual.pdf, p. 30 · FullProf_Manual.pdf, pp. 120–121</td>
</tr>
<tr class="odd">
<td><strong>Anisotropic size, quadratic form</strong></td>
<td>Lorentzian size broadening D_SIZ = k_s d<span class="math inline">\(^{2}\)</span>(SZ1h<span class="math inline">\(^{2}\)</span> + SZ2k<span class="math inline">\(^{2}\)</span> + SZ3l<span class="math inline">\(^{2}\)</span> + SZ4kl + SZ5hl + SZ6hk), an ellipsoidal crystallite.<br>
<span class="m">k_s = (360/π²)λ·<span class="math inline">\(10^{-3}\)</span> in 2<span class="math inline">\(\theta\)</span> and (2/π)Dtt1·<span class="math inline">\(10^{-3}\)</span> in TOF; since 25 May 2006 Size-Model 30 uses the quadratic form with any strain model (Str=1 or 4), no longer only with Str=2 or 3.</span></td>
<td>phase line Str=2 (or -1, 3 with strain); size line SZ1–SZ6</td>
<td class="cite">FullProf_Manual.pdf, p. 25 · FullProf_Manual.pdf, p. 28 · FullProf_Manual.pdf, p. 119 · Microstructural_effects_FP.pdf, p. 7 · Microstructural_effects.pdf, pp. 7–8 · Fullprof_News_2006.htm L291–337</td>
</tr>
<tr class="even">
<td><strong>Anisotropic size, spherical harmonics</strong></td>
<td>Crystallite shape as Σ C_lm Y_lm in Järvinen's normalisation, one model per Laue class (2/m, −3m, m3m with cubic harmonics, mmm, 6/mmm, −3, 4/mmm, −1); Lorentzian only; apparent size per direction listed when an IRF is given.<br>
<span class="m">Microstructural_effects.pdf announces a Gaussian part that "will be introduced"; the mean crystallite shape is drawn by GFourier from the Jvi=5 binary file.</span></td>
<td>Size-Model 15–22</td>
<td class="cite">FullProf_Manual.pdf, pp. 23–24 · FullProf_Manual.pdf, pp. 117–118 · Microstructural_effects_FP.pdf, p. 6 · Microstructural_effects.pdf, pp. 6–7</td>
</tr>
<tr class="odd">
<td><strong>Platelets and needles</strong></td>
<td>Cylindrical crystallites, platelets or needles along a direction [Sz1 Sz2 Sz3].</td>
<td>Size-Model 1, -1</td>
<td class="cite">FullProf_Manual.pdf, p. 25 · FullProf_Manual.pdf, p. 117 · highpress.pcr</td>
</tr>
<tr class="even">
<td><strong>Selective size broadening</strong></td>
<td>Lorentzian 'size' broadening only for reflection classes: up to nine user rules n1h + n2k + n3l = n4·n + n5, one parameter each, or built-in classes (00l, h00, hk0, satellites, parity rules), e.g. antiphase domains in Pd3MnD (Size-Model −14).<br>
<span class="m">A single rule needs Size-Model −2 with a second rule of zeros, to avoid confusion with needles (−1). hkl conditions are real numbers since March 2014 (superstructure reflections); Size-Models 2–14 and −14, broken in some distributions, were restored in April 2022.</span></td>
<td>Size-Model -2…-9 (rules), 2–13 and -14 (built-in classes)</td>
<td class="cite">FullProf_Manual.pdf, p. 24 · FullProf_Manual.pdf, p. 26 · FullProf_Manual.pdf, p. 28 · FullProf_Manual.pdf, pp. 117–118 · pdfinal.pcr L63–64 · Microstructural_effects.pdf, pp. 8–9 · FullProf_News_2014.htm L275–276 · FullProf_News_2022.htm L313–316</td>
</tr>
<tr class="odd">
<td><strong>Defect and stress peak shifts</strong></td>
<td>hkl-dependent shifts: along a reciprocal direction (cos or sin of the angle), selective rules for stacking and twin faults (up to 10), or a generalised quadratic+quartic form per Laue class for residual stress; formulas for 2<span class="math inline">\(\theta\)</span>, TOF and energy.<br>
<span class="m">Shift laws 2<span class="math inline">\(\theta\)</span>_S = 2<span class="math inline">\(\theta\)</span>_B + 2·Shift·d<span class="math inline">\(^{2}\)</span>tanθ·<span class="math inline">\(10^{-2}\)</span>, TOF_S = TOF_B − Shift·d<span class="math inline">\(^{3}\)</span>·Dtt1·<span class="math inline">\(10^{-2}\)</span> (Microstructural_effects.pdf).</span></td>
<td>phase line Sol=1; Shift1 Shift2 Shift3 ModS (<span class="math inline">\(\pm\)</span>1, &lt;−1, 100+Laue)</td>
<td class="cite">FullProf_Manual.pdf, p. 27 · FullProf_Manual.pdf, p. 31 · FullProf_Manual.pdf, pp. 114–116 · highpress.pcr L79 · Microstructural_effects.pdf, p. 9</td>
</tr>
<tr class="even">
<td><strong>Per-reflection width and shift</strong></td>
<td>Free Gaussian and Lorentzian broadening and shift for named reflections, a last resort when no model fits.<br>
<span class="m">Since 5 March 2003.</span><br>
<span class="m">Not in the 2001 manual. Up to 50 per phase and pattern in 2003, 200 since 15 May 2014, when extra Gaussian strain (Delta_U/Sig1) and Lorentzian size (Delta_Y/Gam2) terms were added; TOF_FullProf.pdf uses it for a few high-d OSIRIS reflections.</span></td>
<td>phase line Nsp_Ref &gt; 0; 'Special reflections' table</td>
<td class="cite">Microstructural_effects_FP.pdf, p. 10 · Ca2MnO4_300k.pcr L82–85 · Fullprof_News_2003.htm L1774–1824 · FullProf_News_2014.htm L164–187 · TOF_FullProf.pdf, pp. 9–10 · Microstructural_effects.pdf, pp. 9–10</td>
</tr>
<tr class="odd">
<td><strong>Size and strain in TOF</strong></td>
<td>Size and strain terms in the TOF Gaussian variance (GSIZ, DST) and Lorentzian width (DSIZ, LStr, LSiz).<br>
<span class="m">Renamed in March 2022 (Iso-GStrain, Iso-GSize, Ani-LSize, Iso-LorStrain, Iso-LorSize), to be refined with an IRF; the .mic file covers TOF since then ("It may exist still some bugs").</span></td>
<td>TOF line 27 Z1 (GSIZ), LStr, LSiz</td>
<td class="cite">FullProf_Manual.pdf, p. 109 · FullProf_Manual.pdf, p. 111 · TOF_FullProf.pdf, pp. 2–3 · FullProf_News_2022.htm L360–375</td>
</tr>
<tr class="even">
<td><strong>User size and strain subroutines</strong></td>
<td>Own size or strain models in subroutines SIZE and STRAIN linked with the FullProf library.</td>
<td>Size-Model / Strain-Model with user code</td>
<td class="cite">FullProf_Manual.pdf, p. 32 · FullProf_Manual.pdf, p. 3</td>
</tr>
</tbody>
</table>
</div>
<h2 id="corrections" class="anchored">Intensity corrections</h2>
<div class="table-wrap">
<table class="inventory caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Capability</th>
<th data-quarto-table-cell-role="th">What it does</th>
<th data-quarto-table-cell-role="th">In the <code>.pcr</code></th>
<th data-quarto-table-cell-role="th">Sources</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Lorentz–polarisation by geometry</strong></td>
<td>Lp for Debye–Scherrer or Bragg–Brentano, flat plate with a PSD, transmission flat plate (Stoe), synchrotron, Debye–Scherrer laboratory X-rays, or none for pre-corrected data; K = 0 neutrons, 0.5 unpolarised X-rays, about 0.1 synchrotron.<br>
<span class="m">Ilo=-2 (capillary X-rays) since 19 July 2011.</span></td>
<td>line 4 Ilo=0, 1, 2, 3, -1, -2 (4 and 5 below)</td>
<td class="cite">FullProf_Manual.pdf, p. 70 · FullProf_Manual.pdf, pp. 53–54 · FullProf_News_2011.htm L77–78 · FullProf_News_2011.htm L91–94</td>
</tr>
<tr class="even">
<td><strong>Monochromator polarisation</strong></td>
<td>Polarisation from a monochromator, Cthm = cos<span class="math inline">\(^{2}\)</span>2<span class="math inline">\(\theta\)</span>_M (e.g. 0.8001 or 0.7998 for graphite with Cu Kα).</td>
<td>line 8 Cthm</td>
<td class="cite">FullProf_Manual.pdf, p. 53 · FullProf_Manual.pdf, p. 76 · Tutorial-Y2O3.pdf, p. 6</td>
</tr>
<tr class="odd">
<td><strong>Synchrotron polarisation</strong></td>
<td>Polarisation fraction of a synchrotron beam (or mosaic fraction in transmission).</td>
<td>line 8 Rpolarz with Ilo=3 (or 2)</td>
<td class="cite">FullProf_Manual.pdf, p. 76 · Egypt_qa_database.pcr L11–12</td>
</tr>
<tr class="even">
<td><strong>Preferred orientation, exponential</strong></td>
<td>P = G2 + (1−G2)exp(G1α²) about a direction Pr1 Pr2 Pr3; G1 &gt; 99 keeps only reflections parallel to it.</td>
<td>line 4 Nor=0; phase Pr1 Pr2 Pr3; line 30 Pref1 Pref2</td>
<td class="cite">FullProf_Manual.pdf, p. 54 · FullProf_Manual.pdf, p. 93 · FullProf_Manual.pdf, p. 112</td>
</tr>
<tr class="odd">
<td><strong>Preferred orientation, March–Dollase</strong></td>
<td>Modified March function P = G2 + (1−G2)[(G1 cosα)² + sin<span class="math inline">\(^{2}\)</span>α/G1]^(−3/2): G1 &lt; 1 platy, 1 none, &gt; 1 needles in Bragg–Brentano (opposite in Debye–Scherrer); G2 untextured fraction kept in [0, 1].</td>
<td>line 4 Nor=1; line 30 Pref1 Pref2</td>
<td class="cite">FullProf_Manual.pdf, p. 55 · b8p.pcr L4–5 · b8p.pcr L57–59</td>
</tr>
<tr class="even">
<td><strong>Multi-axial March–Dollase (Nor=2)</strong></td>
<td>Up to five preferred-orientation directions per phase, each with its own March–Dollase parameter and fraction of crystallites, the last fraction set so that they sum to 1.<br>
<span class="m">Since 12 October 2003 (version 2.50).</span></td>
<td>line 4 Nor=2; after the Pref lines NPOD, then per direction h k l, G1 and fraction with codes</td>
<td class="cite">Fullprof_News_2003.htm L309–317 · Fullprof_News_2003.htm L367–497</td>
</tr>
<tr class="odd">
<td><strong>March–Dollase–Wright orientation for anvil cells (Nor=3)</strong></td>
<td>Multi-axial March–Dollase for high-pressure anvil cells with the beam along the load and perpendicular to the image plate, integrated numerically (Wright et al., J. Synchrotron Rad. 3, 112, 1996; 20 steps by default).<br>
<span class="m">Since 12 October 2003 (version 2.50).</span></td>
<td>line 4 Nor=3; NPOD N_Int_steps, then the Nor=2 lines</td>
<td class="cite">Fullprof_News_2003.htm L324–346 · Fullprof_News_2003.htm L409–411 · Fullprof_News_2003.htm L504–573</td>
</tr>
<tr class="even">
<td><strong>Per-reflection intensity correction file</strong></td>
<td>In Rietveld mode a multiplicative factor per reflection read from codfiln_pat.hkl enters the Lp factor, e.g. for a plate of known texture.<br>
<span class="m">Since 8 May 2004.</span></td>
<td>phase Irf=2 with abs(Jbt) = 0, 1, 4, 5; file codfiln_pat.hkl</td>
<td class="cite">Fullprof_News_2004.htm L2584–2637</td>
</tr>
<tr class="odd">
<td><strong>Cylinder absorption</strong></td>
<td>Transmission factor for a cylinder from μR (Debye–Scherrer, capillaries, neutron cans).<br>
<span class="m">A second μR for the second wavelength (2nd-muR, last on the Lambda line) since 4 July 2011.</span></td>
<td>line 8 muR</td>
<td class="cite">FullProf_Manual.pdf, p. 55 · FullProf_Manual.pdf, p. 76 · Egypt_qa_database.pcr L11–12 · FullProf_News_2011.htm L107–111</td>
</tr>
<tr class="even">
<td><strong>Lobanov–Alte da Veiga absorption for cylinders</strong></td>
<td>Absorption correction of Lobanov and Alte da Veiga (6th EPDIC, 1998) for cylindrical samples, for constant-wavelength data and, as Iabscor=4, for TOF.<br>
<span class="m">Since 8 April 2002 (version 2.10).</span></td>
<td>CW flag given only as an equation image on the News page; TOF Iabscor=4</td>
<td class="cite">Fullprof_News_2002.htm L2452–2467</td>
</tr>
<tr class="odd">
<td><strong>Flat-plate absorption</strong></td>
<td>Transmission flat plate exp(−μt/cosθ)/cosθ; symmetric reflection flat samples through muR.</td>
<td>Ilo=2 with muR = μt</td>
<td class="cite">FullProf_Manual.pdf, p. 55 · FullProf_Manual.pdf, p. 76</td>
</tr>
<tr class="even">
<td><strong>Transmission flat plate with a PSD (Ilo=4)</strong></td>
<td>Combined Lorentz–polarisation–absorption correction for transmission through a fixed flat plate (thickness t, absorption μ) seen by a position-sensitive detector, with a fixed incidence angle alpsd.<br>
<span class="m">Since 8 April 2002 (version 2.10).</span></td>
<td>line 4 Ilo=4</td>
<td class="cite">Fullprof_News_2002.htm L2075–2091 · Fullprof_News_2002.htm L2311–2349</td>
</tr>
<tr class="odd">
<td><strong>Layered samples in Bragg–Brentano (Ilo=5)</strong></td>
<td>Symmetric Bragg–Brentano on stacked layers of different phases: each phase gets the absorption of the layers above it and of its own, Corr(p) = Π_{i&lt;p} exp(−2μt_i/sinθ)·(1 − exp(−2μt_p/sinθ))/(2μt_p), μt per phase in RMUA, phases ordered from the surface.<br>
<span class="m">Since 7 April 2004.</span></td>
<td>line 4 Ilo=5; phase RMUA = μt</td>
<td class="cite">Fullprof_News_2004.htm L3102 · Fullprof_News_2004.htm L3418–3437</td>
</tr>
<tr class="even">
<td><strong>TOF absorption</strong></td>
<td>Wavelength-dependent absorption for TOF: flat plate perpendicular to the beam, cylinder, or exp(−cλ²), with refinable ABS1, ABS2.<br>
<span class="m">Iabscor=4 is the Lobanov–Alte da Veiga cylinder correction; since January 2024 its second, fixed parameter is a minimum transmission, "an empirical correction waiting for a better absorption correction formula".</span></td>
<td>line 8 Iabscor=1, 2, 3, 4; ABS1 ABS2</td>
<td class="cite">FullProf_Manual.pdf, p. 76 · FullProf_Manual.pdf, p. 110 · CeO2_PEARL.pcr L10–11 · FullProf_News_2024.htm L233–238</td>
</tr>
<tr class="odd">
<td><strong>Bragg–Brentano microabsorption</strong></td>
<td>Angle-dependent intensity factor 1 − P(h), P(h) = P0 + Cp(<span class="math inline">\(\tau\)</span>/sinθ)(1 − <span class="math inline">\(\tau\)</span>/sinθ), with P0, Cp, <span class="math inline">\(\tau\)</span> refinable.</td>
<td>MORE=1 (3 with background profiles) on line 14; P0 Cp Tau line</td>
<td class="cite">FullProf_Manual.pdf, p. 55 · FullProf_Manual.pdf, p. 84 · ce.pcr L22–24 · Fullprof_News_2003.htm L1233–1236</td>
</tr>
<tr class="even">
<td><strong>Beam overflow at low angle</strong></td>
<td>Below Sent0 the beam is longer than the sample and intensities are scaled by sinθ/sin(Sent0) (a partial correction).</td>
<td>line 9 PSD Sent0</td>
<td class="cite">FullProf_Manual.pdf, p. 70 · FullProf_Manual.pdf, p. 77</td>
</tr>
<tr class="odd">
<td><strong>Extinction (powder)</strong></td>
<td>One extinction parameter per phase for powder TOF data; for single-crystal and integrated data a single SHELX-type parameter.<br>
<span class="m">The manual hopes for Becker–Coppens later (p. 63).</span></td>
<td>TOF line 26 Extinc</td>
<td class="cite">FullProf_Manual.pdf, p. 108 · FullProf_Manual.pdf, p. 110 · FullProf_Manual.pdf, p. 63</td>
</tr>
<tr class="even">
<td><strong>User intensity corrections</strong></td>
<td>A table of correction factors versus the scattering variable, interpolated and applied to Icalc, or an empirical function (polynomial in T, or exponential plus Maxwellian for raw TOF) applied to integrated or profile intensities with propagated variances.</td>
<td>line 4 Cor=1 (file CODFIL.cor), Cor=2 (coefficients)</td>
<td class="cite">FullProf_Manual.pdf, p. 71 · FullProf_Manual.pdf, pp. 130–131 · FullProf_Manual.pdf, p. 9</td>
</tr>
</tbody>
</table>
</div>
<h2 id="phases" class="anchored">Several phases, quantitative analysis</h2>
<div class="table-wrap">
<table class="inventory caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Capability</th>
<th data-quarto-table-cell-role="th">What it does</th>
<th data-quarto-table-cell-role="th">In the <code>.pcr</code></th>
<th data-quarto-table-cell-role="th">Sources</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Several phases per pattern</strong></td>
<td>Up to 16 phases, each with its scale, cell, profile and structure; profile parameters may be shared through codes.</td>
<td>line 4 Nph; one phase block per phase</td>
<td class="cite">FullProf_Manual.pdf, p. 5 · FullProf_Manual.pdf, p. 87 · MgAl2O4s_Rietveld.pcr L84–85</td>
</tr>
<tr class="even">
<td><strong>Quantitative phase analysis</strong></td>
<td>Weight fractions W_j = S_j Z_j M_j V_j/<span class="math inline">\(\tau\)</span>_j / Σ(…) from the scale factors (Hill–Howard), printed with esd's; ATZ = Z·M·f<span class="math inline">\(^{2}\)</span>/<span class="math inline">\(\tau\)</span> per phase, recomputed by the program when given as 0.<br>
<span class="m">ATZ computed when given as 0 since 13 May 2001 (formula corrected April 2002); recomputed after occupancy refinement and written to the new .pcr since December 2014 (version 5.50), so sequential runs follow a changing composition.</span></td>
<td>phase line ATZ</td>
<td class="cite">FullProf_Manual.pdf, pp. 31–32 · FullProf_Manual.pdf, p. 91 · Quantitative Phase Analysis using FullProf.pdf, pp. 7–8 · b8p.pcr L4–5 · Fullprof_News_2001.htm L563–569 · Fullprof_News_2002.htm L1209–1218 · FullProf_News_2014.htm L27–30</td>
</tr>
<tr class="odd">
<td><strong>Brindley microabsorption</strong></td>
<td>Brindley particle-absorption contrast <span class="math inline">\(\tau\)</span> per phase from (μ_j − μ̄)R, tabulated by particle class; computed iteratively from the weight fractions.</td>
<td>phase line 19-4 Brind (or in ATZ)</td>
<td class="cite">FullProf_Manual.pdf, pp. 31–32 · FullProf_Manual.pdf, p. 93 · Quantitative Phase Analysis using FullProf.pdf, pp. 5–7</td>
</tr>
<tr class="even">
<td><strong>Quantitative analysis from stored structure factors</strong></td>
<td>Uses Fcalc written once (Hkl=5) as fixed relative intensities, refining only scale and profile, without atoms; FILE_HKL imports cell and space group from that file.<br>
<span class="m">ATZ stored in the Hkl=5 file since July 2003; FILE_HKL since 9 February 2007, copying space group and cell into the .pcr when they differ.</span></td>
<td>phase Jbt=-3, Irf=2, Nat=0; COMMANDS FILE_HKL n file</td>
<td class="cite">FullProf_Manual.pdf, p. 11 · FullProf_Manual.pdf, p. 89 · FP_COMMANDS.pdf, p. 7 · Egypt_qa_database.pcr L74–79 · Fullprof_News_2003.htm L1297–1305 · Fullprof_News_2007.htm L344–391</td>
</tr>
<tr class="odd">
<td><strong>Amorphous content with an internal standard</strong></td>
<td>Amorphous fraction from a known weighed standard: W_real = W_x·W_s,real/W_s,x and amorphous = 1 − Σ crystalline; done from FullProf's weight fractions, not by a program option.<br>
<span class="m">Paper only (J. Appl. Cryst. 2001); not in the 2001 manual.</span></td>
<td>none (post-processing of the weight fractions)</td>
<td class="cite">Quant-amorphous.pdf, pp. 1–3</td>
</tr>
<tr class="even">
<td><strong>Full-profile phase search (FullProfAPP)</strong></td>
<td>Search-match by Rietveld refinement (after Lutterotti) over all selected CIFs: weight-fraction thresholds decide what is refined or dropped, a figure of merit combines Rwp, cell-volume change, weight fraction, size and strain, and a DeGelder similarity index merges equal phases.<br>
<span class="m">Since 15 July 2023 (FullProfAPP 1.0.0).</span></td>
<td>FullProfAPP: Full-Profile Phase Search protocol (runs fp2k)</td>
<td class="cite">index.html L481–565 · index.html L231–295 · index.html L406–415</td>
</tr>
</tbody>
</table>
</div>
<h2 id="lebail" class="anchored">Le Bail and Pawley fits</h2>
<div class="table-wrap">
<table class="inventory caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Capability</th>
<th data-quarto-table-cell-role="th">What it does</th>
<th data-quarto-table-cell-role="th">In the <code>.pcr</code></th>
<th data-quarto-table-cell-role="th">Sources</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Le Bail fit (profile matching, constant scale)</strong></td>
<td>Fits the pattern from cell, space group and profile only: scale fixed, each integrated intensity iterated with the Rietveld formula; Dum=1 lifts the convergence test.<br>
<span class="m">Convergence test (successive <span class="math inline">\(\chi^2\)</span> within <span class="math inline">\(10^{-3}\)</span>) since November 2005; minimum intensity <span class="math inline">\(10^{-6}\)</span>·Imax since June 2024, against small negative intensities when the background is overestimated.</span></td>
<td>phase Jbt=2 (Irf=0 first run); line 4 Dum=1</td>
<td class="cite">FullProf_Manual.pdf, pp. 14–15 · FullProf_Manual.pdf, p. 89 · FullProf_Manual.pdf, p. 68 · Cocuc_LeBail.pcr L4–5 · Cocuc_LeBail.pcr L32–33 · Fullprof_News_2005.htm L900–908 · FullProf_News_2024.htm L164–165</td>
</tr>
<tr class="even">
<td><strong>Profile matching with fixed relative intensities</strong></td>
<td>Keeps the relative intensities (or |F|) read from a file and refines only the scale.<br>
<span class="m">Jbt=3 works as the manual states since May 2003 (Jbt=-3 already did).</span></td>
<td>phase Jbt=3 or -3, Irf=2</td>
<td class="cite">FullProf_Manual.pdf, p. 15 · FullProf_Manual.pdf, p. 89 · Fullprof_News_2003.htm L1468–1477</td>
</tr>
<tr class="odd">
<td><strong>Extracted intensities file</strong></td>
<td>Writes CODFILn.hkl with h, k, l, multiplicity, intensity (or |F| with Jbt=-2), <span class="math inline">\(\sigma\)</span>, 2<span class="math inline">\(\theta\)</span>, FWHM, and switches Irf to 2 so the next run starts from them.</td>
<td>Jbt=2 or -2; Irf=<span class="math inline">\(0 \to 2\)</span></td>
<td class="cite">FullProf_Manual.pdf, p. 90 · FullProf_Manual.pdf, p. 137 · Tutorial-Y2O3.pdf, p. 8</td>
</tr>
<tr class="even">
<td><strong>Biased Le Bail</strong></td>
<td>Le Bail extraction biased by a partial structure: atoms given in a Jbt=2 phase guide the partition of overlapped intensities.<br>
<span class="m">Not in the 2001 manual. Since May 2003 (version 2.40) the known part biases the partition only in the first run (Irf=0); before, in every run.</span></td>
<td>Jbt=2 with Nat &gt; 0</td>
<td class="cite">Tutorial-Y2O3.pdf, p. 2 · y2o3_biased.pcr L115–122 · Fullprof_News_2003.htm L1468–1477</td>
</tr>
<tr class="odd">
<td><strong>Overlap clusters</strong></td>
<td>Groups overlapped reflections into clusters (closer than RMub × mean FWHM, or weak next to strong by RMuc) and writes CODFILn_cltr.int for integrated-intensity work.<br>
<span class="m">Jvi=12 writes a .pow file for XLENS with the same clustering (March 2007).</span></td>
<td>phase Jvi=11 with Jbt=2; RMub RMuc</td>
<td class="cite">FullProf_Manual.pdf, p. 91 · FullProf_Manual.pdf, p. 93 · Tutorial-Y2O3.pdf, pp. 11–12 · Fullprof_News_2007.htm L311–318</td>
</tr>
<tr class="even">
<td><strong>Refinement against integrated intensities</strong></td>
<td>Least squares on extracted powder intensities (clusters as Σ jLpF<span class="math inline">\(^{2}\)</span>) as pseudo-single-crystal data, alone or with a profile, weighted against it by Rmua; minimises Σ w(G<span class="math inline">\(^{2}\)</span>obs − ΣG<span class="math inline">\(^{2}\)</span>calc)².<br>
<span class="m">The manual says mixing a powder profile with integrated intensities is "still in an exploring stage", one powder profile only (p. 63); Rmuc &gt; 0.9 is "not tested!" (p. 93). Since January 2007 a pattern of integrated intensities can be declared with Int=1 in a multi-pattern file.</span></td>
<td>line 4 Cry=1; phase Irf=4; Ipow=2 in the .int file; Rmua Rmub</td>
<td class="cite">FullProf_Manual.pdf, p. 62 · FullProf_Manual.pdf, p. 93 · FullProf_Manual.pdf, pp. 138–139 · Tutorial-Y2O3.pdf, p. 11 · Fullprof_News_2007.htm L458–476</td>
</tr>
</tbody>
</table>
</div>
<h2 id="constraints" class="anchored">Constraints, restraints, rigid bodies</h2>
<div class="table-wrap">
<table class="inventory caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Capability</th>
<th data-quarto-table-cell-role="th">What it does</th>
<th data-quarto-table-cell-role="th">In the <code>.pcr</code></th>
<th data-quarto-table-cell-role="th">Sources</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Refinement codes</strong></td>
<td>Each parameter carries a code C = sign(a)(10p + |a|): p its number in the matrix, a a multiplier on the shift; 0 means fixed. The number of refined parameters is stated on line 13.</td>
<td>codeword after each value; line 13 Maxs</td>
<td class="cite">FullProf_Manual.pdf, p. 13 · FullProf_Manual.pdf, p. 81 · Cocus-asym.pcr L20</td>
</tr>
<tr class="even">
<td><strong>Strict linear constraints by shared codes</strong></td>
<td>The same parameter number on several parameters ties their shifts with the multipliers (e.g. 21.00 on x = y = z, <span class="math inline">\(\pm\)</span>111.00 for a two-site exchange), across atoms, phases and patterns.</td>
<td>same p in several codewords; multiplier a</td>
<td class="cite">FullProf_Manual.pdf, p. 19 · FullProf_Manual.pdf, p. 127 · MgAl2O4s_Rietveld.pcr L69–78</td>
</tr>
<tr class="odd">
<td><strong>Automatic numbering of codes</strong></td>
<td>The user marks parameters with 1.00 and the program numbers them, leaving no holes in the matrix and updating the count.<br>
<span class="m">Since 9 January 2001 (version 1.8a).</span><br>
<span class="m">Symmetry constraints on cell, positions and β_ij applied automatically since April 2002; constraints for two atoms sharing a site since May 2003.</span></td>
<td>line 4 Aut=1</td>
<td class="cite">FullProf_Manual.pdf, pp. 68–69 · Tutorial-Y2O3.pdf, p. 2 · Fullprof_News_2001.htm L1001–1017 · Fullprof_News_2002.htm L1226–1230 · Fullprof_News_2003.htm L1457–1461</td>
</tr>
<tr class="even">
<td><strong>Keyword refinement (VARY/FIX)</strong></td>
<td>Sets codes by name instead of numbers: scale, x_A, xyz, b_A, occ_A, cell, profile terms, TOF terms, per pattern with _n; site-symmetry constraints applied automatically; FIX_SPC fixes all atoms of a species.<br>
<span class="m">Since 14 May 2002 (on the phase-name line).</span><br>
<span class="m">Not in the 2001 manual. Per-atom forms in COMMANDS since February 2005; global VARY/FIX lines for pattern parameters (background, zero, sycos, ratio, dtt1…) since June 2011 (version 5.10); all-phase keywords since October 2017; TOF keywords and the _n pattern suffix since November 2022.</span></td>
<td>COMMANDS block: VARY, FIX, FIX_SPC (Aut=1)</td>
<td class="cite">FP_COMMANDS.pdf, pp. 1–3 · FP_COMMANDS.pdf, p. 12 · sin_3t2.pcr L41–44 · Fullprof_News_2002.htm L532–649 · Fullprof_News_2005.htm L1642–1692 · FullProf_News_2011.htm L156–178 · FullProf_News_2017.htm L135–145 · FullProf_News_2022.htm L15–24</td>
</tr>
<tr class="odd">
<td><strong>Keyword constraints (EQUAL, PEQU, SAME_BISO)</strong></td>
<td>EQUAL ties named parameters to a parent with multipliers (constraining shifts, across phases and patterns); PEQU_pat and PEQU_pha give one code to a profile or cell parameter over all patterns or all phases; SAME_BISO one Biso per species.<br>
<span class="m">Since 22 March 2012 (version 5.30: FIX_SPC, SAME_Biso).</span><br>
<span class="m">Not in the 2001 manual. PEQU_pat and PEQU_pha since November 2022 (version 7.90), EQUAL described 29 November 2022 ("Not everything has been tested"); FP_COMMANDS says EQUAL "may be some bugs".</span></td>
<td>COMMANDS: EQUAL, PEQU_pat, PEQU_pha, SAME_BISO</td>
<td class="cite">FP_COMMANDS.pdf, pp. 1–4 · sin_3t2.pcr L41–50 · FullProf_News_2012.htm L233–253 · FullProf_News_2022.htm L96–108 · FullProf_News_2022.htm L37–71</td>
</tr>
<tr class="even">
<td><strong>Hard limits on parameters</strong></td>
<td>Lower and upper bounds for chosen parameters, applied during least squares and defining the box for Monte Carlo and simulated annealing.<br>
<span class="m">Cell limits are given on the direct parameters and applied internally to A–F since July 2013.</span></td>
<td>line 4 Nre; line 47 NUMPAR LowLIMIT HighLIMIT</td>
<td class="cite">FullProf_Manual.pdf, p. 68 · FullProf_Manual.pdf, p. 126 · ce2.pcr L59–61 · FullProf_News_2013.htm L110–113</td>
</tr>
<tr class="odd">
<td><strong>Distance restraints</strong></td>
<td>Soft restraints Σ((d_obs − d_calc)/<span class="math inline">\(\sigma\)</span>)² added to <span class="math inline">\(\chi^2\)</span>, weighted by the current reduced <span class="math inline">\(\chi^2\)</span>; each between two atoms with a symmetry operator and translation.<br>
<span class="m">Up to 3500 distance and angle restraints since October 2024.</span></td>
<td>phase line Dis; line 45 At1 At2 Itnum T1 T2 T3 Dist Sigma</td>
<td class="cite">FullProf_Manual.pdf, p. 42 · FullProf_Manual.pdf, pp. 123–124 · k2na1p5.pcr L72–78 · FullProf_News_2024.htm L79</td>
</tr>
<tr class="even">
<td><strong>Angle restraints</strong></td>
<td>Soft restraints on bond angles between three atoms with two operators.<br>
<span class="m">Re-enabled on 12 March 2001 (version 1.9b), with candidate lines from Jdi=3 and ANG_MAX ≠ 0; applied without distance restraints since February 2005.</span></td>
<td>phase line Ang; line 45-1</td>
<td class="cite">FullProf_Manual.pdf, pp. 124–125 · k2na1p5.pcr L79–80 · Fullprof_News_2001.htm L706–712 · Fullprof_News_2005.htm L1630–1635</td>
</tr>
<tr class="odd">
<td><strong>Linear restraints</strong></td>
<td>Soft restraint on any linear combination of refined parameters with a target and <span class="math inline">\(\sigma\)</span>, e.g. site occupancies against a total composition.<br>
<span class="m">Since 8 April 2002 (version 2.10).</span><br>
<span class="m">Not in the 2001 manual. NLI replaced the old Syo flag; the target can be another, varying parameter (number + 1000000) since April 2018, and restraints can depend on temperature (T&gt;, T&lt;) since 2020.</span></td>
<td>line 7 NLI; restraint block</td>
<td class="cite">FullProf-Tutorial-RigidBody.pdf, pp. 4–5 · HoBaCuO-HT.pcr L244–250 · Fullprof_News_2002.htm L1278–1471 · FullProf_News_2018.htm L125–140 · FullProf_News_2020.htm L36–39</td>
</tr>
<tr class="even">
<td><strong>Constraints, restraints and limits from a parameter tree (FullProfAPP)</strong></td>
<td>Linear restraints (coefficients, value, tolerance), hard constraints (coefficients; PEQU_pat for cells across patterns) and limits (low, high, stop or periodic boundary) set by selecting parameters in a tree.<br>
<span class="m">Since 6 May 2024 (FullProfAPP 1.2.11, limits).</span></td>
<td>FullProfAPP: Refinement Parameters context menu</td>
<td class="cite">index.html L676–699</td>
</tr>
<tr class="odd">
<td><strong>Restraint candidates written by the program</strong></td>
<td>After a run with distance output the program writes the candidate distance and angle lines (DCONSTRn.hlp, later CFML_Restraints.tpcr) to paste into the .pcr.<br>
<span class="m">Written per phase as CFML_Restraints_k.tpcr since November 2012.</span></td>
<td>Jdi=3; ANG_MAX ≠ 0 for angles</td>
<td class="cite">FullProf_Manual.pdf, p. 11 · FullProf_Manual.pdf, p. 124 · CFML_Restraints_1.tpcr L1–11 · FullProf_News_2012.htm L138–139</td>
</tr>
<tr class="even">
<td><strong>Rigid bodies</strong></td>
<td>Groups of atoms in internal coordinates (spherical, Cartesian, cylindrical or Z-matrix) placed by a centre and three Euler angles; free atoms can be mixed in and groups distorted in a final step.<br>
<span class="m">The 2001 manual has spherical internal coordinates only; Cartesian, cylindrical and Z-matrix forms (KIND=1–3, Z-matrix coordinates not refinable) came on 12 December 2004, after the Cartesian frame was unified in September 2004; free atoms take N_t since November 2014. Its idealised-molecule option is "not very reliable" (p. 38).</span></td>
<td>phase Jbt=4; P1–P15 per group, KIND, |P6|=1</td>
<td class="cite">FullProf_Manual.pdf, pp. 34–37 · FullProf_Manual.pdf, p. 100 · FullProf-Tutorial-RigidBody.pdf, p. 9 · tutorial-rgb.inf L113–119 · pdd.pcr L31–34 · Fullprof_News_2004.htm L363–437 · Fullprof_News_2004.htm L1577–1586 · FullProf_News_2014.htm L52–64</td>
</tr>
<tr class="odd">
<td><strong>Satellite groups</strong></td>
<td>Groups attached to a parent group (methyl, NH2) with only the rotation <span class="math inline">\(\chi\)</span> free.</td>
<td>|P6| = 2</td>
<td class="cite">FullProf_Manual.pdf, p. 37 · FullProf-Tutorial-RigidBody.pdf, pp. 10–12</td>
</tr>
<tr class="even">
<td><strong>TLS</strong></td>
<td>Translation, libration and screw tensors (6 + 6 + 9) of a rigid group refined with its position (Schomaker–Trueblood).</td>
<td>Jbt=4, |P6| = 5, Furth=21</td>
<td class="cite">FullProf_Manual.pdf, pp. 37–38 · FullProf_Manual.pdf, p. 91 · urea.pcr L29–30</td>
</tr>
<tr class="odd">
<td><strong>Molecule to .pcr (Mol_tpcr)</strong></td>
<td>Console program that turns a molecule (CFL or Z-matrix .FHZ) into rigid-body .pcr blocks or complete .pcr files ready for simulated annealing.<br>
<span class="m">Since 10 March 2005.</span><br>
<span class="m">Not in the 2001 manual. On the toolbar Programs menu since February 2016; writes three .pcr files prepared for simulated annealing since June 2024.</span></td>
<td>external program; output .tpcr</td>
<td class="cite">FullProf-Tutorial-RigidBody.pdf, pp. 15–19 · tutorial-rgb.inf L43–56 · Fullprof_News_2005.htm L1229–1252 · FullProf_News_2016.htm L166–169 · FullProf_News_2024.htm L173–178</td>
</tr>
</tbody>
</table>
</div>
<h2 id="engine" class="anchored">The least-squares engine</h2>
<div class="table-wrap">
<table class="inventory caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Capability</th>
<th data-quarto-table-cell-role="th">What it does</th>
<th data-quarto-table-cell-role="th">In the <code>.pcr</code></th>
<th data-quarto-table-cell-role="th">Sources</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Least-squares minimiser</strong></td>
<td>Minimises <span class="math inline">\(\chi^2\)</span> = Σ w_i(y_i − yc_i)² by Gauss–Newton normal equations; each shift is multiplied by its code multiplier and a relaxation factor.</td>
<td>built in</td>
<td class="cite">FullProf_Manual.pdf, pp. 42–43 · la0.log L33–35</td>
</tr>
<tr class="even">
<td><strong>Cycles and convergence</strong></td>
<td>Up to NCY cycles; stops when all shifts are below Eps × esd (0.2 or less advised).</td>
<td>line 9 NCY Eps</td>
<td class="cite">FullProf_Manual.pdf, p. 77 · la0.log L49</td>
</tr>
<tr class="odd">
<td><strong>Relaxation factors</strong></td>
<td>Four damping factors on shifts by class: atomic (R_at), anisotropic (R_an), profile and cell (R_pr), global such as zero and background (R_gl); rotations of rigid bodies need about three times more damping.</td>
<td>line 9 R_at R_an R_pr R_gl</td>
<td class="cite">FullProf_Manual.pdf, p. 77 · FullProf_Manual.pdf, p. 39 · Cocuc_LeBail.pcr L13–14</td>
</tr>
<tr class="even">
<td><strong>Stop on divergence</strong></td>
<td>Stops when <span class="math inline">\(\chi^2\)</span> rises from one cycle to the next.<br>
<span class="m">Since October 2011 the program finishes smoothly instead of interrupting the run.</span></td>
<td>line 4 Dum=2</td>
<td class="cite">FullProf_Manual.pdf, p. 68 · FullProf_News_2011.htm L28–30</td>
</tr>
<tr class="odd">
<td><strong>Local divergence control</strong></td>
<td>A parameter that diverges locally is reset to its previous value and the multiplier of its code halved for the next cycle, with a warning, instead of being fixed to an arbitrary value.<br>
<span class="m">Since 12 October 2003 (version 2.50).</span></td>
<td>built in</td>
<td class="cite">Fullprof_News_2003.htm L240–248</td>
</tr>
<tr class="even">
<td><strong>Standard deviations</strong></td>
<td><span class="math inline">\(\sigma\)</span>(α_k) = √((A<span class="math inline">\(^{-1}\)</span>)_kk <span class="math inline">\(\chi^2\)</span>_ν), with <span class="math inline">\(\chi^2\)</span>_ν counted over points with Bragg contributions (also reported over all points).</td>
<td>built in</td>
<td class="cite">FullProf_Manual.pdf, p. 43</td>
</tr>
<tr class="odd">
<td><strong>Agreement factors</strong></td>
<td>Rp, Rwp, Rexp, <span class="math inline">\(\chi^2\)</span>, conventional (background-subtracted) cRp, cRwp, Bragg R and R_F per phase, Iobs by Rietveld partition, each over all points and over points with Bragg contributions; printed each cycle.<br>
<span class="m">R_Bragg and R_F correct for intensities far below counts since April 2011.</span></td>
<td>built in</td>
<td class="cite">FullProf_Manual.pdf, pp. 43–44 · la0.log L37–47 · FullProf_News_2011.htm L247–252</td>
</tr>
<tr class="even">
<td><strong>Model-selection statistics</strong></td>
<td>Deviance, Akaike and Schwarz criteria, Durbin–Watson d with its 99.9 % threshold QD.</td>
<td>built in</td>
<td class="cite">FullProf_Manual.pdf, p. 45 · la0_120.sum L196–215</td>
</tr>
<tr class="odd">
<td><strong>Refinement analysis</strong></td>
<td>Appends to the summary an analysis of the refinement: effective number of reflections and expected R-factors from a Poisson simulation.</td>
<td>line 7 Ana=1</td>
<td class="cite">FullProf_Manual.pdf, pp. 61–62 · FullProf_Manual.pdf, p. 75</td>
</tr>
<tr class="even">
<td><strong>Bérar factor for correlated residuals</strong></td>
<td>Prints the factor by which esd's should be multiplied for serially correlated residuals (Bérar &amp; Lelann 1991), e.g. 1.77.<br>
<span class="m">Not in the 2001 manual; seen in .out files of version 5.30 (2012) and later.</span></td>
<td>built in (.out)</td>
<td class="cite">LaMnO3ref.out L796–799</td>
</tr>
<tr class="odd">
<td><strong>Correlation matrix</strong></td>
<td>Writes the correlation matrix, or prints the matrix diagonal every cycle; the manual advises refining separately parameters correlated above 50 %.<br>
<span class="m">Correlations above 50 % listed with symbolic parameter names since April 2002.</span></td>
<td>line 7 Mat=1, 2</td>
<td class="cite">FullProf_Manual.pdf, p. 72 · FullProf_Manual.pdf, p. 14 · Fullprof_News_2002.htm L976–982</td>
</tr>
<tr class="even">
<td><strong>Faster calculation</strong></td>
<td>Optimised routines, up to about 30 % faster; reflections re-sorted every cycle or only at the first.<br>
<span class="m">The optimised mode skips the Bragg R factors each cycle and is to be switched off if results go wrong (January 2001).</span></td>
<td>line 4 Opt=1; Ias</td>
<td class="cite">FullProf_Manual.pdf, p. 68 · Fullprof_News_2001.htm L1039–1046</td>
</tr>
<tr class="odd">
<td><strong>Array dimensions from fullprof.dim</strong></td>
<td>Dynamic allocation sized by a fullprof.dim file (current directory or the FULLPROF path): MaxPOINT, MaxREFLX, MaxPARAM, MaxOVERL, default 30000 points, 9000 reflections, 250 free parameters, 1024 overlapping reflections.<br>
<span class="m">Since 12 March 2001 (version 1.9b).</span><br>
<span class="m">A static build was also distributed until October 2002.</span></td>
<td>file fullprof.dim; environment variable FULLPROF</td>
<td class="cite">Fullprof_News_2001.htm L748–838 · Fullprof_News_2002.htm L290–294</td>
</tr>
<tr class="even">
<td><strong>Parallel build</strong></td>
<td>A parallel executable fp2k_par runs the same tests.<br>
<span class="m">Not in the 2001 manual; nothing is said about what it parallelises.</span></td>
<td>command line fp2k_par</td>
<td class="cite">test_fp_par.bat L1–3</td>
</tr>
</tbody>
</table>
</div>
<h2 id="workflow" class="anchored">Workflow: running, sequences, programs around it, the live display</h2>
<div class="table-wrap">
<table class="inventory caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Capability</th>
<th data-quarto-table-cell-role="th">What it does</th>
<th data-quarto-table-cell-role="th">In the <code>.pcr</code></th>
<th data-quarto-table-cell-role="th">Sources</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Command-line run</strong></td>
<td>Run as <code>fp2k code [datafile] [logfile]</code>, reading code.pcr and the data file and sending screen output to a log for batch use; without arguments it prompts for both.</td>
<td>command line</td>
<td class="cite">FullProf_Manual.pdf, pp. 6–7 · test_fp.bat L1–3</td>
</tr>
<tr class="even">
<td><strong>The .pcr control file</strong></td>
<td>One text file holds flags, data description, phases and codes, in free (ordered) format with ! comments, in single- or multi-pattern layout; rewritten at the end of each run with refined values and comment headers (including current <span class="math inline">\(\chi^2\)</span> and R_Bragg), or written to CODFIL.new.<br>
<span class="m">Comments written automatically on rewriting since January 2001; tab characters accepted since November 2023.</span></td>
<td>whole file; line 7 Pcr=1, 2</td>
<td class="cite">FullProf_Manual.pdf, p. 8 · FullProf_Manual.pdf, pp. 65–66 · FullProf_Manual.pdf, p. 72 · Cocus-excl.pcr L1–5 · Fullprof_News_2001.htm L1165–1171 · FullProf_News_2023.htm L16–18</td>
</tr>
<tr class="odd">
<td><strong>Debugging listing of the .pcr</strong></td>
<td>The keyword print_pcr in the title line makes the program echo each .pcr line as it is read into debug_PCR.lst, to locate reading errors that give no message.<br>
<span class="m">Since 27 November 2006 (version 3.76).</span></td>
<td>print_pcr in line 1 of the .pcr</td>
<td class="cite">Fullprof_News_2006.htm L23–29</td>
</tr>
<tr class="even">
<td><strong>Sequential refinement</strong></td>
<td>Refines a numbered series of data files in turn, each run starting from the previous .pcr; results go to a summary file and, in later versions, a .seq table of all parameters for plotting (71 patterns <span class="math inline">\(\times 1535\)</span> points, 21 parameters in 26 s in the WinPLOTR example).<br>
<span class="m"><code>fp2k cyc …</code> with .seq output since February 2004, keep/delete flags for output files since November 2007, keyword seq since February 2008; arguments a1–a7 and a -temp file of sample temperatures since September 2013; intermediate .sum and .out files kept since 2020 and 2024.</span></td>
<td>command line: code CYC (2001) or <code>fp2k seq …</code> ; Rpa</td>
<td class="cite">FullProf_Manual.pdf, p. 7 · test_fp.bat L50–51 · FPS_dec2015_WinPLOTR_TR.pdf, pp. 18–21 · Fullprof_News_2004.htm L4737–4777 · Fullprof_News_2007.htm L36–89 · Fullprof_News_2008.htm L297–299 · FullProf_News_2013.htm L54–98 · FullProf_News_2020.htm L44 · FullProf_News_2024.htm L71–72</td>
</tr>
<tr class="odd">
<td><strong>Sequential multi-pattern refinement</strong></td>
<td>Sequential mode with several patterns per temperature (e.g. neutrons and X-rays): the data name multi_pattern makes FullProf increment the codename_n.ext files named in the .pcr at each step; TOF banks in one file share one code.<br>
<span class="m">Since 2 April 2014.</span></td>
<td><code>[w]fp2k seq code multi_pattern n1 n2 y y y y y n</code></td>
<td class="cite">FullProf_News_2014.htm L209–255 · FullProf_News_2014.htm L125–139 · FullProf_News_2017.htm L250–256 · FullProf_News_2020.htm L82–84</td>
</tr>
<tr class="even">
<td><strong>Keyword commands</strong></td>
<td>A COMMANDS…END_COMMANDS block after the phase name (up to 20 keywords per phase) for refinement keywords, d-limits, constraints and extra outputs; VARY/FIX also on the phase-name line or after the wavelength line.<br>
<span class="m">Since 15 January 2005.</span><br>
<span class="m">Not in the 2001 manual, whose keyword format "is not available at present" (p. 8); before 2005 keywords such as VARY and DLIM went on the phase-name line. FP_Commands.pdf on the toolbar since September 2023, replaced in April 2025 when the command handling changed.</span></td>
<td>COMMANDS block</td>
<td class="cite">FP_COMMANDS.pdf, p. 1 · ce1.pcr L13–14 · rutana_tch.pcr L29 · Fullprof_News_2005.htm L1727–1737 · FullProf_News_2023.htm L75–77 · FullProf_News_2025.htm L46–48</td>
</tr>
<tr class="odd">
<td><strong>Windows console with stop prompt</strong></td>
<td>The Windows program wfp2k is the console program in a window; it asks whether to continue or stop the refinement.<br>
<span class="m">Replaced in May 2007 by the Winteracter wfp2k (next entry).</span></td>
<td>program wfp2k</td>
<td class="cite">FullProf_Manual.pdf, p. 6 · FullProf_Manual.pdf, p. 16 · Fullprof_News_2007.htm L180–191</td>
</tr>
<tr class="even">
<td><strong>wfp2k graphic window</strong></td>
<td>The Winteracter wfp2k (Windows, Linux) runs a .pcr in a split window (log above, pattern below), re-runs it, calls EdPCR, and has a sequential mode with a dialog; it sets Ls2=4 to draw the pattern and is slower than the console fp2k, kept for scripts.<br>
<span class="m">Since 8 May 2007 (version 4.00).</span></td>
<td>program wfp2k; menus Load, Edit PCR, Mode, Run</td>
<td class="cite">Fullprof_News_2007.htm L180–230 · Fullprof_News_2007.htm L134–150</td>
</tr>
<tr class="odd">
<td><strong>Live display during refinement</strong></td>
<td>Observed and calculated patterns redrawn on screen at each cycle while FullProf runs from WinPLOTR or the toolbar; integrated-intensity clusters shown evolving during simulated annealing.<br>
<span class="m">The 2001 manual says "in some versions" only. fp_studio_dyn shows the structure evolving (an .fst each cycle, Ls2=5 with Jvi=3) since July 2004; WinPLOTR-2006 redraws an open .prf as FullProf rewrites it since August 2024.</span></td>
<td>line 7 Ls2=4 (2001); GUI</td>
<td class="cite">FullProf_Manual.pdf, p. 73 · Tutorial-Y2O3.pdf, p. 6 · FullProf-Tutorial-Symmetry-Modes.pdf, p. 12 · Fullprof_News_2004.htm L1964–1975 · FullProf_News_2024.htm L99–101</td>
</tr>
<tr class="even">
<td><strong>WinPLOTR Rietveld plot</strong></td>
<td>Plots the .prf file (Yobs, Ycalc, difference, Bragg ticks, excluded regions) with zoom, cursor in 2<span class="math inline">\(\theta\)</span> and d, hkl shown on click; shown automatically at the end of a run; x in 2<span class="math inline">\(\theta\)</span>, TOF, energy, Q, d; series in pseudo-3D.</td>
<td>GUI (reads .prf)</td>
<td class="cite">FullProf_Manual.pdf, p. 4 · FPS_dec2015_WinPLOTR_TR.pdf, pp. 3–4 · FPS_dec2015_WinPLOTR_TR.pdf, p. 7 · Tutorial_Co_doped_YBCO.pdf, p. 13</td>
</tr>
<tr class="odd">
<td><strong>WinPLOTR-2006</strong></td>
<td>Rewrite of WinPLOTR with Winteracter for Windows, Linux and macOS: OpenGL 3D views of pattern series, multi-file opening saved as buffer files, choice of fp2k or wfp2k, .seq plots; peak fitting since June 2009.<br>
<span class="m">Since 6 February 2006 (beta).</span></td>
<td>GUI</td>
<td class="cite">Fullprof_News_2006.htm L452–498 · Fullprof_News_2007.htm L148–152 · Fullprof_News_2009.htm L120–143</td>
</tr>
<tr class="even">
<td><strong>Interactive background points</strong></td>
<td>Background points picked with the mouse on the pattern or .prf (or placed automatically, about √n points, "not recommended for advanced analysis"), edited and saved for pasting into the .pcr.<br>
<span class="m">Not in the 2001 manual.</span></td>
<td>GUI (WinPLOTR) → Nba=N point list</td>
<td class="cite">FPS_dec2015_WinPLOTR_TR.pdf, pp. 38–40 · FullProf-Tutorial-Symmetry-Modes.pdf, pp. 10–11</td>
</tr>
<tr class="odd">
<td><strong>Interactive peak search and fitting</strong></td>
<td>Automatic peak search with thresholds and Kα-doublet option; single-peak fitting with TCH pseudo-Voigt from mouse clicks (background ends, top, FWHM), with progress windows; peak list feeds indexing.<br>
<span class="m">Not in the 2001 manual. Axial-divergence asymmetry and TOF single peaks since January 2004; the WinPLOTR-2006 fitting "completely operational" in June 2015 (up to 120 background points and 300 peaks, .pik files).</span></td>
<td>GUI (WinPLOTR)</td>
<td class="cite">FPS_dec2015_WinPLOTR_TR.pdf, pp. 24–25 · Tutorial_Co_doped_YBCO.pdf, p. 9 · Tutorial-Y2O3.pdf, p. 4 · Fullprof_News_2004.htm L4910–4915 · FullProf_News_2015.htm L140–163</td>
</tr>
<tr class="even">
<td><strong>EdPCR</strong></td>
<td>Dialog editor of the .pcr (refinement mode, phases, atoms, codes) with an internal text editor; converts CIF and SHELX .ins to .pcr.<br>
<span class="m">Not in the 2001 manual. The symmetry-mode tutorial reports an EdPCR bug with that option (p. 21). In the Suite by 2003: IRF templates (May 2003), most FullProf options and .pcr files from scratch (June 2003), a TOF "Simple calculations" template (TOF_FullProf.pdf, Dec. 2003); NEdPCR beta with wizards in July 2010; Chebyshev backgrounds since October 2017.</span></td>
<td>GUI</td>
<td class="cite">Tutorial-Y2O3.pdf, pp. 13–17 · FPS_dec2015_WinPLOTR_TR.pdf, p. 9 · Fullprof_News_2003.htm L1374–1383 · Fullprof_News_2003.htm L1443–1449 · TOF_FullProf.pdf, pp. 8–9 · FullProf_News_2010.htm L41–45 · FullProf_News_2017.htm L131–132</td>
</tr>
<tr class="odd">
<td><strong>GetControl</strong></td>
<td>A .pcr editor by P. Beran for Windows, Linux and macOS, launched from the toolbar, with information on each variable of the .pcr.<br>
<span class="m">Since 25 April 2026 (on the toolbar).</span></td>
<td>GUI (toolbar)</td>
<td class="cite">FullProf_News_2026.htm L84–98</td>
</tr>
<tr class="even">
<td><strong>CIFs_to_PCR</strong></td>
<td>Console utility that merges CIF files listed in a buffer file into one multiphase .pcr, optionally with an IRF; multi-pattern files from a .c2pcr input or a toolbar dialog (October 2017), simulation files (January 2022), ICSD :R/:H symbols (April 2022).<br>
<span class="m">Since 19 May 2016.</span></td>
<td><code>CIFs_to_PCR file.buf [Res irf]</code>, <code>CIFs_to_PCR -file x.c2pcr</code>; toolbar Tools &gt; CIFs_to_PCR</td>
<td class="cite">FullProf_News_2016.htm L143–159 · FullProf_News_2017.htm L116–129 · FullProf_News_2022.htm L420–424 · FullProf_News_2022.htm L280–284 · FullProf_News_2024.htm L36–39</td>
</tr>
<tr class="odd">
<td><strong>FullProf Suite toolbar</strong></td>
<td>Launcher that sets the working directory and starts WinPLOTR, FullProf, EdPCR, Check_Group, GFourier and FullProf Studio on the loaded files.<br>
<span class="m">Since 30 March 2007 (version 3.90).</span><br>
<span class="m">Not in the 2001 manual. Crystallographic calculator since June 2009, VESTA button since October 2014; a PySide6 version (GetControl, BasIrreps, a FullProf Studio with Fourier maps, nDataRed) in testing in 2026, with separate Ubuntu and Mint builds.</span></td>
<td>GUI</td>
<td class="cite">Tutorial-Y2O3.pdf, pp. 2–3 · Tutorial-Y2O3.pdf, p. 10 · Tutorial-Y2O3.pdf, p. 18 · Fullprof_News_2007.htm L277–299 · Fullprof_News_2009.htm L94–118 · FullProf_News_2014.htm L72–80 · FullProf_News_2026.htm L135–137 · FullProf_News_2026.htm L96–103 · FullProf_News_2026.htm L54–58</td>
</tr>
<tr class="even">
<td><strong>FullProf Studio</strong></td>
<td>3D viewer of the refined structure from .fst files (polyhedra, mode displacements as arrows), with continuous reading to follow a simulated-annealing run.<br>
<span class="m">Since 14 July 2004 (alpha).</span><br>
<span class="m">Not in the 2001 manual. By L. Chapon (ISIS); Winteracter version November 2004, polyhedra April 2007, version 2 September 2008.</span></td>
<td>GUI; .fst written by FullProf</td>
<td class="cite">Tutorial-Y2O3.pdf, p. 18 · FullProf-Tutorial-Symmetry-Modes.pdf, p. 9 · Fullprof_News_2004.htm L1832–1922 · Fullprof_News_2004.htm L877–914 · Fullprof_News_2007.htm L245–253 · Fullprof_News_2008.htm L75–78</td>
</tr>
<tr class="odd">
<td><strong>FullProfAPP</strong></td>
<td>Python GUI (CIC energiGUNE) for batches: import patterns, extract background, fetch CIFs from COD, full-profile phase search, automatic refinement protocols, sequential and multi-pattern grids, contour plots of series; not a superset of FullProf (no modes, magnetism, single crystal or annealing).<br>
<span class="m">Since 15 July 2023 (FullProfAPP 1.0.0).</span><br>
<span class="m">Not in the 2001 manual. Windows and Linux only, constant-wavelength patterns (TOF "will come in future versions"); fp2k jobs run in parallel since August 2023 (1.1.0, about four times faster); manual v1.3.3 of 9 June 2025.</span></td>
<td>GUI; writes .pcr</td>
<td class="cite">Presentation.pdf, pp. 3–5 · Exercise-EgyptMakeup.pdf, p. 1 · Exercise-LiFePO4.pdf, pp. 1–2 · index.html L406–415 · index.html L400 · FullProf_News_2023.htm L100–103 · index.html L218</td>
</tr>
<tr class="even">
<td><strong>Project state file (FullProfAPP)</strong></td>
<td>Saves and loads the interface state as an INI file with a .fpapp extension: state variables and data locations, not the data.</td>
<td>FullProfAPP: File &gt; Save, Load</td>
<td class="cite">index.html L130–153</td>
</tr>
<tr class="odd">
<td><strong>Batch and multi-pattern grid (FullProfAPP)</strong></td>
<td>Patterns imported in groups (or from a .buf list) form a grid: each row with a checked cell is a separate refinement job, each column a pattern refined simultaneously (e.g. X-rays + neutrons); each group has one radiation, geometry and wavelength.</td>
<td>FullProfAPP: Import Pattern, Pattern Checks</td>
<td class="cite">index.html L170 · index.html L206–228 · index.html L332 · index.html L347–351</td>
</tr>
<tr class="even">
<td><strong>Peak detection (FullProfAPP)</strong></td>
<td>Peaks found after background subtraction with prominence and width thresholds, Kα1–Kα2 doublets recognised; editable and exported with the background as a three-column file.</td>
<td>FullProfAPP: Pattern &gt; Peak Detection; API PeakFindCalculator</td>
<td class="cite">index.html L243–252 · index.html L149–158 · calculators.html L289–300</td>
</tr>
<tr class="odd">
<td><strong>CIF download from the COD (FullProfAPP)</strong></td>
<td>Periodic-table query (each element required, optional or excluded) through OPTIMADE, CIFs downloaded from the COD into the working folder or read from a local folder; a materials table with formula, space group and cell.</td>
<td>FullProfAPP: Materials menu, Queried/Selected Materials</td>
<td class="cite">index.html L170–201 · index.html L266–267 · index.html L405–427</td>
</tr>
<tr class="even">
<td><strong>Interactive simulation of candidate phases (FullProfAPP)</strong></td>
<td>Simulates selected phases against the focused pattern with sliders for each scale and the zero shift, reflections moved with the cell parameters, and a CIF written with the adjusted cell.</td>
<td>FullProfAPP: Simulate Selection</td>
<td class="cite">index.html L206–224 · index.html L414</td>
</tr>
<tr class="odd">
<td><strong>Automatic refinement workflow (FullProfAPP)</strong></td>
<td>A refinement built as a list of steps from a checkable parameter tree (each step adds VARY/FIX lines) and run on every checked pattern, from a .pcr made by CIFs_to_PCR with the extracted background; phases below 2 % weight fraction are dropped; step lists saved as JSON.<br>
<span class="m">Since 15 July 2023 (FullProfAPP 1.0.0).</span><br>
<span class="m">The manual says the JSON load/save "is prone to fail".</span></td>
<td>FullProfAPP: Automatic Refinement Protocol</td>
<td class="cite">index.html L570–615 · index.html L700–712 · index.html L716–728 · index.html L735–739 · index.html L770</td>
</tr>
<tr class="even">
<td><strong>Sequential mode (FullProfAPP)</strong></td>
<td>Refines all patterns between the first and last checked one, each from the previous result, forwards or backwards by load order; optionally with each pattern's own extracted background.</td>
<td>FullProfAPP: Sequential Mode</td>
<td class="cite">index.html L220 · index.html L611–615 · index.html L756–767</td>
</tr>
<tr class="odd">
<td><strong>Manual refinement window (FullProfAPP)</strong></td>
<td>The .pcr as editable tables with dependent counts (Nba, Nex, Nat) kept consistent, check boxes for microabsorption, bond valences, phase shifts and anisotropic terms, and COMMANDS with autocompletion.<br>
<span class="m">Since 9 April 2025 (FullProfAPP 1.3.2, COMMANDS).</span></td>
<td>FullProfAPP: Manual Refinement</td>
<td class="cite">index.html L776–807 · index.html L140–141</td>
</tr>
<tr class="even">
<td><strong>Python modules for .pcr and output files (FullProfAPP)</strong></td>
<td>The fpfunctions API: PcrIO edits single- and multi-pattern .pcr files; readers for .sum, .prf, .mic, IRF and CIF folders, and FAULTS .flts files.<br>
<span class="m">Since 27 March 2025 (FullProfAPP 1.3.0, API documented).</span><br>
<span class="m">Methods are listed without descriptions.</span></td>
<td>FullProfAPP API</td>
<td class="cite">index.html L100 · app_io.html L1180–1187 · app_io.html L905–911 · app_io.html L763–769 · app_io.html L4089–4100</td>
</tr>
<tr class="odd">
<td><strong>WinPLOTR batch commands</strong></td>
<td>Command files for WinPLOTR to convert formats, normalise, shift, subtract, transform x (2<span class="math inline">\(\theta\)</span>, Q, d…), fit single peaks or Cu/Mo/Co doublets, and export images, over many files.<br>
<span class="m">Not in the 2001 manual.</span></td>
<td><code>winplotr file.cmd</code></td>
<td class="cite">FPS_dec2015_WinPLOTR_TR.pdf, pp. 42–44</td>
</tr>
<tr class="even">
<td><strong>Refinement strategy guidance</strong></td>
<td>Documented order: scale; zero, background, cell; positions and overall B; shape and asymmetry; occupancies; isotropic then anisotropic B; SyCos/SySin; microstructure. Le Bail first to fix cell and profile.</td>
<td>documentation</td>
<td class="cite">FullProf_Manual.pdf, p. 14 · Tutorial_Co_doped_YBCO.pdf, p. 10</td>
</tr>
<tr class="odd">
<td><strong>Example and test suite</strong></td>
<td>An example kit (pcr_dat.zip) with the 2001 manual; the current FP_tests folder has 130 .pcr files run by test_fp.bat, and a digest program (Get_Log) collects CPU time and <span class="math inline">\(\chi^2\)</span> of every run.<br>
<span class="m">TOF_FullProf.pdf lists the TOF examples of 2003 (SEPD, POLARIS, PEARL, OSIRIS, HRPD); FullProf_Examples_testing.zip, run by test_fp.bat or test_fp.sh in 5–10 minutes, distributed since September 2022.</span></td>
<td>test_fp.bat</td>
<td class="cite">FullProf_Manual.pdf, pp. 16–17 · test_fp.bat L1–3 · log.res L1–5 · TOF_FullProf.pdf, p. 9 · FullProf_News_2022.htm L120–133</td>
</tr>
<tr class="even">
<td><strong>User subroutines</strong></td>
<td>Own structure-factor, magnetic, size and strain models in subroutines STRMOD, MAGMOD, SIZE, STRAIN linked with the FULLP library.</td>
<td>phase Jbt=4/5 user routines</td>
<td class="cite">FullProf_Manual.pdf, p. 3 · FullProf_Manual.pdf, p. 32</td>
</tr>
<tr class="odd">
<td><strong>iPowder</strong></td>
<td>A Python interface to FullProf from Z. Feng's team, simpler than FullProfAPP: search-match, indexing and basic manual and automatic Rietveld refinement with FullProf as engine, X-rays only, for beginners (J. Appl. Cryst. 58, 296, 2025).<br>
<span class="m">Since 20 May 2026 (linked from the FullProf page).</span></td>
<td>external GUI</td>
<td class="cite">FullProf_News_2026.htm L60–72</td>
</tr>
<tr class="even">
<td><strong>Builds for Windows, Linux and macOS</strong></td>
<td>The Suite is distributed for Linux since January 2004 (with a reduced WinPLOTR) and for Windows, Linux and macOS since April 2008, built with several Fortran compilers; in 2008 some Mac GUIs did not work yet, the console programs did; a Mac installer bundle came in July 2010.<br>
<span class="m">Since 26 January 2004 (Linux); 30 April 2008 (macOS, version 4.30).</span></td>
<td>distribution</td>
<td class="cite">Fullprof_News_2004.htm L4871–4878 · Fullprof_News_2008.htm L234–245 · FullProf_News_2010.htm L29–32</td>
</tr>
</tbody>
</table>
</div>
<h2 id="output" class="anchored">Output files</h2>
<div class="table-wrap">
<table class="inventory caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Capability</th>
<th data-quarto-table-cell-role="th">What it does</th>
<th data-quarto-table-cell-role="th">In the <code>.pcr</code></th>
<th data-quarto-table-cell-role="th">Sources</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Main listing (.out)</strong></td>
<td>All input, reflections, correlations, obs/calc intensities and per-cycle parameters; optional line-printer plot, reflection lists and profile listing.</td>
<td>always; line 7 Ipr=1, Ppl=1, Ioc, Ls1, Ls3, Sho</td>
<td class="cite">FullProf_Manual.pdf, p. 9 · FullProf_Manual.pdf, pp. 72–73</td>
</tr>
<tr class="even">
<td><strong>Summary (.sum)</strong></td>
<td>Last-cycle parameters with esd's and R-factors.</td>
<td>always</td>
<td class="cite">FullProf_Manual.pdf, pp. 9–10 · la0_120.sum L196–220</td>
</tr>
<tr class="odd">
<td><strong>Plot file (.prf)</strong></td>
<td>Observed, calculated, difference, background, reflection positions and hkl per pattern, for WinPLOTR and other plotting programs.</td>
<td>line 7 Prf=1–4 (later -3)</td>
<td class="cite">FullProf_Manual.pdf, p. 9 · FullProf_Manual.pdf, p. 73 · la0.prf L1–6</td>
</tr>
<tr class="even">
<td><strong>Anomalous-scattering difference patterns</strong></td>
<td>For X-ray patterns at several wavelengths, writes near-edge minus far-from-edge differences of observed and calculated patterns after removing background and Lp, on a common s = 1/d (.pgf files for WinPLOTR); Anm=2 adds resonant minus simulated non-resonant .prf files.<br>
<span class="m">Since 14 April 2004 (version 2.70).</span></td>
<td>Anm after Cor: -1 far from the edge, 1 or 2 near the edge</td>
<td class="cite">Fullprof_News_2004.htm L2974–3075 · Fullprof_News_2004.htm L2724–2757</td>
</tr>
<tr class="odd">
<td><strong>Reflection lists (.hkl)</strong></td>
<td>h, k, l, multiplicity, d, 2<span class="math inline">\(\theta\)</span>, FWHM, Iobs, Icalc; or for EXPO/SIRPOW, real and imaginary F, F<span class="math inline">\(^{2}\)</span> with <span class="math inline">\(\sigma\)</span>, or Fcalc for quantitative analysis.</td>
<td>line 7 Hkl=1–5</td>
<td class="cite">FullProf_Manual.pdf, p. 11 · FullProf_Manual.pdf, pp. 74–75</td>
</tr>
<tr class="even">
<td><strong>Fourier files (.fou)</strong></td>
<td>Observed structure factors for Fourier maps in CCSL/FOURTK, SHELXS (+.ins), FOURIER or GFOURIER (+.inp) formats; Fcalc in absolute units if negative.<br>
<span class="m">Fou=4 with Jbt=2, 3 gives Patterson maps through GFourier (January 2003); Fou=<span class="math inline">\(\pm\)</span>6 A, B lists (December 2008) and Dysnomia maximum-entropy files (July 2017); Fou=7 SuperFlip and EDMA inputs (May 2012).</span></td>
<td>line 7 Fou=1–7</td>
<td class="cite">FullProf_Manual.pdf, p. 10 · FullProf_Manual.pdf, p. 75 · Tutorial-Y2O3.pdf, p. 10 · Fullprof_News_2003.htm L2346–2351 · Fullprof_News_2008.htm L15–17 · FullProf_News_2012.htm L181–187 · FullProf_News_2017.htm L166–179</td>
</tr>
<tr class="odd">
<td><strong>Per-phase profiles (.sub)</strong></td>
<td>Calculated profile of each phase, with or without background.</td>
<td>line 7 Ipr=2, 3</td>
<td class="cite">FullProf_Manual.pdf, p. 12 · FullProf_Manual.pdf, p. 73</td>
</tr>
<tr class="even">
<td><strong>Background file (.bac)</strong></td>
<td>Writes the refined background, or the difference pattern, as a file.</td>
<td>line 7 Ppl=2, 3</td>
<td class="cite">FullProf_Manual.pdf, p. 73 · Tutorial-Y2O3.pdf, pp. 6–7</td>
</tr>
<tr class="odd">
<td><strong>Microstructure file (.mic)</strong></td>
<td>Per reflection integral breadths, apparent size and strain; averages whose spread measures anisotropy (not error); 99999 means no size broadening.<br>
<span class="m">Since 9 January 2001 (version 1.8a, "still under construction").</span><br>
<span class="m">Breadths in Å⁻¹ <span class="math inline">\(\times 1000\)</span>, strains in %% × <span class="math inline">\(10^{4}\)</span> (Microstructural_effects.pdf). Also for TOF since March 2022; size and strain shapes as VESTA .pgrid/.ggrid since October 2014.</span></td>
<td>Res≠0 with Npr=7</td>
<td class="cite">FullProf_Manual.pdf, pp. 11–12 · FullProf_Manual.pdf, p. 25 · Microstructural_effects_FP.pdf, p. 8 · Fullprof_News_2001.htm L1081–1087 · Microstructural_effects.pdf, p. 8 · FullProf_News_2022.htm L373–375 · FullProf_News_2014.htm L82–83</td>
</tr>
<tr class="even">
<td><strong>Directional size and strain files (.str, .siz, .bin)</strong></td>
<td>Apparent size and strain along crystallographic directions in codfil_size_n.siz and codfil_strain_n.str, with esd's since February 2005, and binary files from which GFourier draws the mean crystallite shape in 3D.<br>
<span class="m">Since 8 April 2002 (version 2.10).</span></td>
<td>phase Jvi=5 (with an IRF)</td>
<td class="cite">Fullprof_News_2002.htm L1491–1496 · Fullprof_News_2002.htm L519–525 · Fullprof_News_2005.htm L1563–1569 · Microstructural_effects.pdf, p. 7</td>
</tr>
<tr class="odd">
<td><strong>Distances and bond valences (.dis)</strong></td>
<td>Distances, angles and bond-valence sums per phase.</td>
<td>phase Jdi=3, 4</td>
<td class="cite">FullProf_Manual.pdf, p. 11 · FullProf_Manual.pdf, p. 92</td>
</tr>
<tr class="even">
<td><strong>Sequential summaries (.rpa, .sav, .seq)</strong></td>
<td>Short summary appended run after run, and a reflection list between two angles for sequential work.<br>
<span class="m">Rpa=-2 writes the .seq table of refined parameters with symbolic names (February 2004), Rpa=-3 rewrites it (February 2008); WinPLOTR plots several .seq files together.</span></td>
<td>line 7 Rpa=1, 2, -2, -3; line 51</td>
<td class="cite">FullProf_Manual.pdf, p. 9 · FullProf_Manual.pdf, p. 11 · FullProf_Manual.pdf, p. 72 · FullProf_Manual.pdf, p. 129 · Fullprof_News_2004.htm L4737–4746 · Fullprof_News_2008.htm L288–295 · Fullprof_News_2008.htm L317–325</td>
</tr>
<tr class="odd">
<td><strong>Symmetry operators (.sym)</strong></td>
<td>Symmetry operators of each phase.<br>
<span class="m">Redefined in April 2002 as detailed symmetry information for all phases (formerly BONDSTR input).</span></td>
<td>line 7 Syo=1, Sym=1</td>
<td class="cite">FullProf_Manual.pdf, p. 10 · FullProf_Manual.pdf, p. 72 · Fullprof_News_2002.htm L1265–1285</td>
</tr>
<tr class="even">
<td><strong>Structure files for drawing programs</strong></td>
<td>Atoms of the cell (.atm), SCHAKAL or STRUPLO input (.sch), rigid-body coordinates for Molview, Balls &amp; Sticks and ORTEP.</td>
<td>phase More=1 with Jdi, Jvi</td>
<td class="cite">FullProf_Manual.pdf, p. 12 · FullProf_Manual.pdf, p. 39 · FullProf_Manual.pdf, p. 91</td>
</tr>
<tr class="odd">
<td><strong>CIF, CFL, FST and VESTA files</strong></td>
<td>Refined structure as CIF (and profile CIF), CrysFML .cfl, FullProf Studio .fst and VESTA files; bond-valence .bvs.<br>
<span class="m">Since 15 October 2002 (version 2.20, CIF).</span><br>
<span class="m">Not in the 2001 manual. Structure and profile CIFs for powders since September 2003, distances in the CIF since March 2008, one CIF per pattern since March 2012.</span></td>
<td>written by current versions</td>
<td class="cite">PPH3-sls.cif L1–6 · Tutorial-Y2O3.pdf, p. 21 · era.bat L30–34 · Fullprof_News_2002.htm L301–389 · Fullprof_News_2003.htm L824–828 · Fullprof_News_2008.htm L265–266 · FullProf_News_2012.htm L228–231</td>
</tr>
<tr class="even">
<td><strong>Simulated pattern (.sim)</strong></td>
<td>Calculated pattern with Poisson noise in Ins=0 format.</td>
<td>abs(Job)&gt;1 with Dum=1</td>
<td class="cite">FullProf_Manual.pdf, p. 12 · FullProf_Manual.pdf, p. 69</td>
</tr>
<tr class="odd">
<td><strong>Screen log</strong></td>
<td>Per-cycle R-factors and <span class="math inline">\(\chi^2\)</span> as on screen, kept as .log when given on the command line.</td>
<td>third command-line argument</td>
<td class="cite">FullProf_Manual.pdf, p. 7 · la0.log L37–47</td>
</tr>
<tr class="even">
<td><strong>Summary plots of a series (FullProfAPP)</strong></td>
<td>Plots chosen refined parameters (weight fractions, cell, strain, with esd's) against pattern number, updated after each pattern, and exports them as x, y text with pattern names.</td>
<td>FullProfAPP: Summary tab</td>
<td class="cite">index.html L308–320 · index.html L193–194 · index.html L275</td>
</tr>
</tbody>
</table>
</div>
<h2 id="later" class="anchored">Kept for later</h2><ul class="k-list"><li><b>Magnetic structures.</b> Commensurate and incommensurate magnetic structures: moments in the magnetic cell or by propagation vectors (up to 24), Fourier components, helices, cones, basis functions of irreps, Shubnikov groups, magnetic R-factor. <span class="cite">FullProf_Manual.pdf, p. 6 · FullProf_Manual.pdf, pp. 19–20 · FullProf_Manual.pdf, pp. 89–90 · FullProf_Manual.pdf, pp. 96–99 · Ca_m_m_a.pcr L53</span></li><li><b>Modulated structures and superspace.</b> Commensurate displacement modulations (Jbt=<span class="math inline">\(\pm\)</span>15) in the 2001 manual; magnetic superspace groups (Jbt=<span class="math inline">\(\pm\)</span>7) in the tests. <span class="cite">FullProf_Manual.pdf, pp. 106–107 · DyMnGe_SuperSpace.pcr L72</span></li><li><b>Stacking faults.</b> FAULTS, a separate program of the Suite (DIFFaX-based) that refines powder patterns of layered crystals with planar defects; inside FullProf, selective broadening and shifts, and LAYER_x for turbostratic layers ("still at a testing stage"). <span class="cite">Faults_Manual.pdf, pp. 4–5 · FP_COMMANDS.pdf, p. 5</span></li><li><b>Indexing.</b> DICVOL, TREOR and ITO launched from WinPLOTR on its peak list, which then writes a Le Bail .pcr per solution. <span class="cite">FPS_dec2015_WinPLOTR_TR.pdf, p. 8 · Tutorial-Y2O3.pdf, pp. 4–5</span></li><li><b>Structure solution.</b> Space-group search (Check_Group), Monte Carlo and simulated annealing on integrated intensities or profile points, with rigid bodies and symmetry modes; Fourier and Patterson maps via GFourier. GLOpSAnn (October 2008, updated April 2020) solves structures by simulated annealing from a CFL file with 12 weighted cost functions (intensities, profile, restraints, bond valence, Coulomb, anti-bump). <span class="cite">FullProf_Manual.pdf, pp. 126–129 · Tutorial-Y2O3.pdf, pp. 8–9 · pb_san.pcr L66–67 · GLOpSAnn.pdf, pp. 1–5</span></li><li><b>Pair distribution function.</b> Calc_PDF (2013) calculated a PDF from a CFL file; MolPDF (version 0.7, October 2016) replaced it and refines a structure against G(r) from several patterns and phases by Levenberg–Marquardt, with restraints, intramolecular sharpening and a sphere-size distribution for nanocrystals, "still in a testing stage". <span class="cite">FPS_dec2015_WinPLOTR_TR.pdf, p. 11 · FullProf_News_2013.htm L35–52 · FullProf_News_2016.htm L19–29 · Short_guide_to_MolPDF.pdf, pp. 1–3</span></li><li><b>Bond-valence maps and energy landscapes.</b> (G)Bond_Str computes bond-valence-sum maps (2015), bond-valence energy landscapes with percolation energies (2017) for ionic conduction paths (J. Appl. Cryst. 52, 148, 2019). <span class="cite">FullProf_News_2015.htm L254–258 · FullProf_News_2017.htm L188–195 · FullProf_News_2019.htm L316–324</span></li></ul>
<h2 id="out" class="anchored">Out of scope</h2><ul class="k-list"><li><b>Single-crystal data.</b> Integrated intensities of single crystals (F<span class="math inline">\(^{2}\)</span> or F, twins with up to 6 hkl per observation, domain scales, extinction, λ/2), alone or with powder data. <span class="cite">FullProf_Manual.pdf, p. 5 · FullProf_Manual.pdf, pp. 62–63 · FullProf_Manual.pdf, pp. 138–139 · prnio.pcr L1–5</span></li><li><b>Polarised-neutron flipping ratios.</b> Single-crystal flipping-ratio refinement with a multipole form factor, seen only in the tests. <span class="cite">100K_c_vert-fr0.pcr L29–32 · 100K-c_vert.int L3</span></li><li><b>Electron diffraction.</b> Single-crystal electron-diffraction F<span class="math inline">\(^{2}\)</span> data treated kinematically with Mott–Bethe scattering factors (Job=4, since 22 July 2006, version 3.70; Cry=4 simulates an electron pattern), for refinement or simulated annealing; Mol_tpcr's JOB 4 writes such .pcr files. No dynamical (3D ED) refinement is documented. <span class="cite">FullProf-Tutorial-RigidBody.pdf, p. 19 · Fullprof_News_2006.htm L235–257</span></li></ul>
<h2 id="not-found" class="anchored">Not found in the material</h2><ul class="k-list"><li>Pawley fitting: the manual names Pawley's method only as a relative of profile matching (FullProf_Manual.pdf p. 14); FullProf implements Le Bail.</li><li>Surface-roughness corrections (Suortti, Pitschke and others) by name: only the Bragg–Brentano microabsorption P0/Cp/<span class="math inline">\(\tau\)</span> correction, whose references [25], [26] are not listed in the 2001 manual (p. 55).</li><li>Thin-sample transparency shift: the manual gives the formula but says the correction "is not implemented in FullProf" (p. 56).</li><li>Texture as a spherical-harmonic orientation distribution: FullProf has the exponential and March–Dollase functions, multi-axial March–Dollase (Nor=2, up to five directions, 2003), its anvil-cell variant (Nor=3) and a per-reflection correction file for a known external texture (2004); the QPA paper used external pole figures (Quantitative-prefOrient.pdf).</li><li>Sabine-type powder extinction for constant-wavelength data: only one TOF powder parameter and a SHELX-type single-crystal parameter (pp. 63, 110).</li><li>Fundamental-parameters peak shapes (emission profile, slits, detector convolved from geometry): only the Finger–Cox–Jephcoat axial-divergence term.</li><li>hkl-dependent asymmetry: "No hkl-dependent asymmetry model is currently available" (p. 31).</li><li>Amorphous-phase modelling as a phase (other than Debye-like background terms or the internal-standard calculation).</li><li>General 2D image integration (image plates, area detectors): WinPLOTR-2006 only displays ILL single-crystal detector frames (D9, D10, D15, D19; News 13 August 2007, 24 June 2009), and Get_Data integrates only the ILL D2B detector (2023).</li></ul>
</article>


<!-- Closes the reading column opened by _gen/docs-nav.html, adds the right
     "On this page" list, and wires: current-page marking in the left nav,
     breadcrumbs, the page TOC (from h2/h3 in the reading column) and a
     scroll-spy. Pure DOM, no library. -->
  </div>
  <aside class="docs-toc"><button class="docs-fold" type="button" data-fold="toc" aria-label="Hide the page outline" title="Hide the page outline">›</button><div class="t">On this page</div><ol></ol></aside>
</div>
<script>
(function () {
  /* 0. The two side panels fold on their chevrons; the choice is remembered in this browser. */
  var docs = document.querySelector('.docs');
  if (docs) {
    var store = {};
    try { store = JSON.parse(localStorage.getItem('docs-fold') || '{}'); } catch (e) { store = {}; }
    function apply() {
      docs.classList.toggle('nav-folded', !!store.nav);
      docs.classList.toggle('toc-folded', !!store.toc);
      document.querySelectorAll('.docs-fold').forEach(function (b) {
        var which = b.getAttribute('data-fold'), folded = !!store[which];
        b.innerHTML = (which === 'nav') === folded ? '&rsaquo;' : '&lsaquo;';
        var what = which === 'nav' ? 'the navigation' : 'the page outline';
        b.title = (folded ? 'Show ' : 'Hide ') + what; b.setAttribute('aria-label', b.title);
      });
    }
    document.querySelectorAll('.docs-fold').forEach(function (b) {
      b.addEventListener('click', function () {
        var which = b.getAttribute('data-fold'); store[which] = !store[which];
        try { localStorage.setItem('docs-fold', JSON.stringify(store)); } catch (e) {}
        apply();
      });
    });
    apply();
  }
  /* 0b. The header ribbon: mark the entry whose section holds this page. Quarto rewrites the hrefs to
     relative paths, so folders are read from the resolved URLs; the Overview link gives the site root. */
  (function () {
    var links = Array.prototype.slice.call(document.querySelectorAll('.site-nav a'));
    if (!links.length) return;
    /* a served URL may end in '/' (GitHub Pages: …/about/); read it as …/about/index.html */
    function folder(path) { if (/\/$/.test(path)) path += 'index.html'; var s = path.split('/').filter(Boolean); return s.length > 1 ? s[s.length - 2] : ''; }
    var wm = document.querySelector('a.wordmark');            // the wordmark links to the site root
    var root = folder((wm || links[0]).pathname);
    var map = { 'focus-literature': 'validation', user: 'manual', theory: 'manual' };
    function key(path) { var f = folder(path); if (f === root) return 'overview'; return map[f] || f; }
    var here = key(location.pathname);
    links.forEach(function (a) { a.classList.toggle('current', key(a.pathname) === here); });
  })();

  var main = document.querySelector('.docs-main');
  var nav = document.querySelector('.docs-nav');
  var toc = document.querySelector('.docs-toc ol');
  if (!main || !nav || !toc) return;

  /* 1. Left nav: mark the current page (and section, if the hash matches). */
  var here = location.pathname.replace(/\/index\.html$/, '/');
  var links = Array.prototype.slice.call(nav.querySelectorAll('a'));
  var pageLink = null, hashLink = null;
  links.forEach(function (a) {
    var p = a.pathname.replace(/\/index\.html$/, '/');
    if (p !== here) return;
    if (!a.hash && !pageLink) pageLink = a;
    if (a.hash && a.hash === location.hash) hashLink = a;
  });
  var cur = hashLink || pageLink;
  if (cur) {
    cur.classList.add('current');
    var det = cur.closest('details.group');
    if (det) { det.open = true; det.classList.add('has-current'); }
    /* Breadcrumbs: group title › page (› section). */
    var crumbs = document.createElement('div');
    crumbs.className = 'docs-crumbs';
    var g = det ? det.querySelector('summary.t') : null;
    var parts = [];
    function push(t) { if (t && parts[parts.length - 1] !== t) parts.push(t); }
    if (g) push(g.textContent.trim());
    if (pageLink && pageLink !== cur) push(pageLink.textContent.trim());
    push(cur.textContent.trim());
    crumbs.innerHTML = parts.map(function (t, i) {
      return (i ? '<span class="sep">›</span>' : '') + '<span>' + t.replace(/</g, '&lt;') + '</span>';
    }).join('');
    main.insertBefore(crumbs, main.firstChild);
  }

  /* 2. Right "On this page": h2 and h3 of the reading column. */
  var used = {};
  var heads = Array.prototype.slice.call(main.querySelectorAll('h2, h3')).filter(function (h) {
    if (h.closest('.site-foot, .featured-band, .msg-grid, [data-toc="no"]')) return false;
    if (h.classList.contains('unnumbered') || h.id === 'contenido') return false;
    return h.textContent.trim().length > 0;
  });
  heads.forEach(function (h) {
    if (!h.id) {
      var s = h.textContent.trim().toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '')
        .replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60) || 'sec';
      while (used[s] || document.getElementById(s)) s += '-';
      h.id = s;
    }
    used[h.id] = true;
    var li = document.createElement('li');
    if (h.tagName === 'H3') li.className = 'l3';
    var a = document.createElement('a');
    a.href = '#' + h.id;
    /* This runs before KaTeX has rendered the headings, so a heading with mathematics still holds TeX
       source: copy its markup, including the math spans, and let the page's KaTeX pass render the copy. */
    var copy = h.cloneNode(true);
    copy.querySelectorAll('.katex-mathml, annotation, .anchorjs-link').forEach(function (n) { n.remove(); });
    var label = copy.textContent.trim().replace(/\s+/g, ' ');
    if (copy.querySelector('.math, .math-done, .katex')) a.innerHTML = copy.innerHTML.trim();
    else a.textContent = label.length > 72 ? label.slice(0, 70).replace(/[\s,;:]+\S*$/, '') + '…' : label;
    a.title = label;
    li.appendChild(a);
    toc.appendChild(li);
  });
  if (!heads.length) { document.querySelector('.docs-toc').hidden = true; return; }

  /* 3. Scroll-spy. */
  var items = Array.prototype.slice.call(toc.querySelectorAll('a'));
  function spy() {
    var y = window.scrollY + 120, best = null;
    heads.forEach(function (h) { if (h.getBoundingClientRect().top + window.scrollY <= y) best = h; });
    items.forEach(function (a) { a.classList.toggle('current', best && a.getAttribute('href') === '#' + best.id); });
  }
  window.addEventListener('scroll', spy, { passive: true });
  window.addEventListener('hashchange', spy);
  spy();
})();
</script>
<footer class="site-foot">
  <div class="site-foot__inner">
    <div class="foot-grid">
      <div class="foot-about">
        <h4 class="anchored">What this is</h4>
        <p>The working site of one project: to build a Mac app for Rietveld refinement of powder diffraction data, after a study of the programs the community uses for it. It holds the brief, that study, the design, a dated log of every step, the release notes and the manuals of the core and the app.</p>
        <div class="cite-block">Josu M. Igartua · Departamento de Física, UPV/EHU<br>josu.igartua@ehu.eus</div>
      </div>
      <div><h4 class="anchored">This site</h4><ul>
        <li><a href="../../index.html">Overview</a></li><li><a href="../../brief/index.html">Brief</a></li><li><a href="../../background/index.html">Background</a></li><li><a href="../../design/index.html">Design</a></li><li><a href="../../roadmap/index.html">Roadmap</a></li><li><a href="../../log/index.html">Log</a></li><li><a href="../../about/index.html">Method</a></li></ul></div>
      <div><h4 class="anchored">Sources</h4><ul>
        <li><a href="https://doi.org/10.1107/S0021889869006558">Rietveld 1969</a></li>
        <li><a href="https://www.ill.eu/sites/fullprof/">FullProf Suite</a></li>
        <li><a href="https://advancedphotonsource.github.io/GSAS-II-tutorials/">GSAS-II</a></li>
        <li><a href="https://it.iucr.org/A/">International Tables, Vol. A</a></li></ul></div>
      <div><h4 class="anchored">Status</h4><ul>
        <li>Published at <a href="https://jmigartua.github.io/diff-ref-struct-site/">jmigartua.github.io/diff-ref-struct-site</a>; the sources are private</li>
        <li>Rebuilt from <code>data/*.yml</code> on every render</li></ul></div>
    </div>
    <div class="foot-bottom">
      <span>© 2026 Josu M. Igartua · work in progress</span>
      <span>Quarto · family design kit</span>
    </div>
  </div>
</footer>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
    tabsets.forEach(function(tabset) {
      const tabby = new Tabby('#' + tabset.id);
    });
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>